In [5]:
%matplotlib widget

import os
import mne
import tqdm
import pytz
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from tqdm import tqdm
from pathlib import Path
from mne.io import concatenate_raws, read_raw_edf
from edf2parquet.readers import ParquetReader
from edf2parquet.converters import EdfToParquetConverter, AdvancedEdfToParquetConverter

from bscarlos.settings import RAW_KISPI_DATA_FOLDER
from bscarlos.settings import PROCESSED_KISPI_DATA_FOLDER

# ETL
Here we explore the extract the raw data (.edf) from KISPI patients and their corresponding annotations (.txt) from our `RAW_KISPI_DATA_FOLDER`.

We transform the data into more managable `pandas.dataframes` with the goal to combine the annotations which are our 'ground_truth' labels.

In the end we should have a dataframe for each patients containing 17-bipolar channel columns and 1-ground truth column.

We load/export our newly merged dataframes stored as `.parquet` files accomanied with a `data_attributes.csv` file into our `PROCESSED_KISPI_DATA_FOLDER`.

### Convert .edf to parquet files
In order to better handle the dataset it would be advantagous to create a dataframe using trusty `pandas`, however we first needed to convert our EEG files from .edf format into parquet files.

To accomplish this we used the `edf2parquet` a simple utility package to convert EDF/EDF+ files into Apache Parquet format while preserving the EDF file header information and signal headers metadata information then we will be able to read the files directly<sup>1</sup>. 

We specifically used the built-in `AdvancedEdfToParquetConverter` class to convert the files and utilize the `exclude_singals` argument to exclude the following list of signals ["EEG A1", "EEG A2", "EKG", "EOG", "EMG", "PHO", "NASE"].  

In addition we create a data_attributes.csv file with all the important attributes we unvail.

---


[1] [edf2parquet repository](https://github.com/NarayanSchuetz/edf2parquet/tree/main)

This is just a quick test of the converter uncomment `#test_converter.convert()` to produce output.

In [2]:
test_edf_file = str(RAW_KISPI_DATA_FOLDER / Path("SE008_120418U-A.edf"))
test_parquet_output_dir = RAW_KISPI_DATA_FOLDER

test_converter = AdvancedEdfToParquetConverter(edf_file_path=test_edf_file,  # path to the EDF file
                                          # excluded signals     
                                          exclude_signals=["Audio"],  
                                          # output directory path
                                          parquet_output_dir=test_parquet_output_dir,
                                          # grouping signals with same sampling frequency
                                          group_by_sampling_freq=True,  
                                          # add a pd.DatetimeIndex to the resulting parquet files
                                          datetime_index=True,
                                          # specifies timezone location and start_date of the EDF file
                                          local_timezone=(pytz.timezone("Europe/Zurich"), pytz.timezone("Europe/Zurich")),
                                          # compression codec
                                          compression_codec="GZIP" 
                                          )

#test_converter.convert()

### Correct .edf header 'subject code' and 'admincode' for all annotated data files
Reason for this is that it causes issues when creating the data_attributes.csv file

- [x] This was completed manually using `EDFBrowser`'s Tools -> "Header editor repair"

## Extract
We extract the files we want from our `RAW_KISPI_DATA_FOLDER` and save them into a list `filenames`

We will keep to list `filenames_a1` for our annotations from annotator1 and `filenames_a2` for our annotations from annotator2.

That way we avoid cross contamination of ground truth labels which could potentially ruin our end inter-rater agreement analysis.

We only make the list `filenames` containing all files to produce our `data_attributes.csv` file later.

In [3]:
# define the input and output folders
input_folder = RAW_KISPI_DATA_FOLDER
output_folder = PROCESSED_KISPI_DATA_FOLDER

# create the output folder if it doesn't exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# get a list of all .edf files in the input folder
filenames_a1 = [filename for filename in os.listdir(input_folder) if filename.__contains__("annotated1") and filename.endswith('.edf')]
filenames_a2 = [filename for filename in os.listdir(input_folder) if filename.__contains__("annotated2") and filename.endswith('.edf')]
filenames = filenames_a1 + filenames_a2

#### TO DO: Add Andreas files and annotations
- [ ] add SE008_annotated2
- [ ] add SE008_annotated2_annotations.txt
- [ ] add SE026_annotated2
- [ ] add SE026_annotated2_annotations.txt

In [4]:
print(filenames)
print(filenames_a1)
print(filenames_a2)

['SE008_annotated1.edf', 'SE021_annotated1.edf', 'SE026_annotated1.edf', 'SE038_annotated1.edf', 'SE021_annotated2.edf', 'SE038_annotated2.edf']
['SE008_annotated1.edf', 'SE021_annotated1.edf', 'SE026_annotated1.edf', 'SE038_annotated1.edf']
['SE021_annotated2.edf', 'SE038_annotated2.edf']

## Transform

### Convert Annotator-1 files

#### TO DO: Correct filename output
currently outputs: 'SE021 a1_2015-09-01_256.0'

goal: 'SE021_a1'

In [5]:
# convert all .edf files
for filename in tqdm(filenames_a1, desc='Converting EDF to Parquet'):
    # instantiate the AdvancedEdfToParquetConverter
    converter = AdvancedEdfToParquetConverter(
        edf_file_path=os.path.join(input_folder, filename),
        parquet_output_dir=output_folder,
        exclude_signals=["EEG A1", "EEG A2", "EKG", "EOG", "EMG", "PHO", "NASE"],
        group_by_sampling_freq=True,
        datetime_index=True,
        local_timezone=(pytz.timezone("Europe/Zurich"), pytz.timezone("Europe/Zurich")),
        compression_codec="GZIP"
    )
    
    # convert the EDF file to Parquet and save it to the output folder
    #converter.convert()

Converting EDF to Parquet:   0%|          | 0/4 [00:00<?, ?it/s]

Converting EDF to Parquet: 100%|██████████| 4/4 [00:00<00:00,  5.28it/s]

#### Read Converted Parquet Annotator-1 Files 
using handy pandas.

In [6]:
SE008_a1_parquet_file_path = PROCESSED_KISPI_DATA_FOLDER / Path("SE008_a1.parquet")
SE021_a1_parquet_file_path = PROCESSED_KISPI_DATA_FOLDER / Path("SE021_a1.parquet")
SE026_a1_parquet_file_path = PROCESSED_KISPI_DATA_FOLDER / Path("SE026_a1.parquet")
SE038_a1_parquet_file_path = PROCESSED_KISPI_DATA_FOLDER / Path("SE038_a1.parquet")

# convert WindowsPath to strings (to avoid encoding errors)
SE008_a1_parquet_file_path = str(SE008_a1_parquet_file_path)
SE021_a1_parquet_file_path = str(SE021_a1_parquet_file_path)
SE026_a1_parquet_file_path = str(SE026_a1_parquet_file_path)
SE038_a1_parquet_file_path = str(SE038_a1_parquet_file_path)

a1_parquet_file_paths = [SE008_a1_parquet_file_path, SE021_a1_parquet_file_path, SE026_a1_parquet_file_path, SE038_a1_parquet_file_path]

#### Read Converted Parqeut Annotator-1 File 
using the `ParquetReader` directly tranfrom into pandas_df

In [7]:
from edf2parquet.readers import ParquetReader

read_SE021_a1 = ParquetReader(parquet_file_path=SE021_a1_parquet_file_path)
SE021_a1_df = pd.read_parquet(SE021_a1_parquet_file_path, engine='pyarrow')

Read one file and get file header

In [8]:
read_SE021_a1.get_file_header()

{'technician': '',
 'recording_additional': '',
 'patientname': 'X',
 'patient_additional': '',
 'patientcode': 'SE021 a1',
 'equipment': 'Deltamed',
 'admincode': 'SE021 150901U-C 0000',
 'sex': '',
 'startdate': Timestamp('2015-09-01 16:06:27+0200', tz='Europe/Zurich'),
 'birthdate': '',
 'gender': '',
 'tz_recording': 'Europe/Zurich',
 'tz_startdatetime': 'Europe/Zurich'}

Read rest of files, get header, transform into df's

In [9]:
read_SE008_a1 = ParquetReader(parquet_file_path=SE008_a1_parquet_file_path)
SE008_a1_df = pd.read_parquet(SE008_a1_parquet_file_path, engine='pyarrow')

read_SE026_a1 = ParquetReader(parquet_file_path=SE026_a1_parquet_file_path)
SE026_a1_df = pd.read_parquet(SE026_a1_parquet_file_path, engine='pyarrow')

read_SE038_a1 = ParquetReader(parquet_file_path=SE038_a1_parquet_file_path)
SE038_a1_df = pd.read_parquet(SE038_a1_parquet_file_path, engine='pyarrow')

In [10]:
print(read_SE008_a1.get_file_header())
print(read_SE026_a1.get_file_header())
print(read_SE038_a1.get_file_header())

{'technician': '', 'recording_additional': '', 'patientname': 'X', 'patient_additional': '', 'patientcode': 'SE008 a1', 'equipment': 'Deltamed', 'admincode': 'SE008 120418U-A', 'sex': '', 'startdate': Timestamp('2012-04-17 17:02:08+0200', tz='Europe/Zurich'), 'birthdate': '', 'gender': '', 'tz_recording': 'Europe/Zurich', 'tz_startdatetime': 'Europe/Zurich'}
{'technician': '', 'recording_additional': '', 'patientname': 'X', 'patient_additional': '', 'patientcode': 'SE026 a1', 'equipment': 'Deltamed', 'admincode': 'SE026 140520Q-A', 'sex': '', 'startdate': Timestamp('2014-05-20 08:30:52+0200', tz='Europe/Zurich'), 'birthdate': '', 'gender': '', 'tz_recording': 'Europe/Zurich', 'tz_startdatetime': 'Europe/Zurich'}
{'technician': '', 'recording_additional': '', 'patientname': 'X', 'patient_additional': '', 'patientcode': 'SE038 a1', 'equipment': 'Deltamed', 'admincode': 'SE038 180523D-D', 'sex': '', 'startdate': Timestamp('2018-05-23 11:05:57+0200', tz='Europe/Zurich'), 'birthdate': '', 'gender': '', 'tz_recording': 'Europe/Zurich', 'tz_startdatetime': 'Europe/Zurich'}

#### Filter Data
Based on annotation lengths

##### Filter SE008_a1
by its unique `cutoff_time_SE008`

In [11]:
print(SE008_a1_df.shape)

(15010560, 19)

In [12]:
SE008_a1_df = SE008_a1_df.copy()
SE008_a1_df.index = SE008_a1_df.index.tz_localize(None)

In [13]:
SE008_a1_df.head(-1)

,EEG Fp1,EEG Fp2,EEG F7,EEG F3,EEG Fz,EEG F4,EEG F8,EEG T3,EEG C3,EEG Cz,EEG C4,EEG T4,EEG T5,EEG P3,EEG Pz,EEG P4,EEG T6,EEG O1,EEG O2
2012-04-17 17:02:08.000000,107.303505,78.486382,163.326843,136.478592,-6.354085,123.591438,143.638138,102.649803,41.435799,84.392998,104.797668,-5.280156,121.980545,138.805450,73.116730,30.338522,-16.377432,63.988327,160.463028
2012-04-17 17:02:08.003906,107.303505,78.665367,164.400772,136.120621,-6.354085,121.622566,142.922180,101.217896,39.466927,81.350197,102.470818,-6.175097,119.653694,135.225677,70.073929,28.011673,-17.451363,61.482491,157.062256
2012-04-17 17:02:08.007812,108.914398,80.634239,167.980545,138.626465,-5.996109,123.412453,145.428009,103.723732,39.824902,81.887161,104.081711,-4.922179,118.937744,135.762650,71.147858,28.190662,-15.124514,59.513618,158.136185
2012-04-17 17:02:08.011718,108.914398,80.992218,167.443573,138.805450,-5.459144,123.591438,146.143967,102.470818,39.108948,82.424126,105.871597,-3.490272,118.400780,136.120621,73.116730,30.159533,-13.513618,58.439690,159.568100
2012-04-17 17:02:08.015625,108.556419,81.529182,166.727631,137.552536,-3.311284,124.486382,145.964981,101.575874,38.929962,84.392998,107.661476,-1.342412,120.190659,137.731522,75.622566,32.844357,-11.723736,60.229572,162.073929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-04-18 09:19:22.976562,116.789886,45.552528,300.252930,105.334633,-1.521401,108.198441,-1210.766479,138.626465,104.439690,6.712062,107.482491,31.054474,-34.813229,28.011673,-100.143967,24.610895,57.902725,-674.159546,122.696495
2012-04-18 09:19:22.980468,115.715950,45.015564,298.105072,110.883270,46.089493,108.377434,-1048.424072,135.762650,101.038910,4.385214,108.198441,32.307392,-36.603111,26.579767,-102.291832,23.357977,56.649807,-674.338501,121.264595
2012-04-18 09:19:22.984375,117.147858,45.015564,299.357971,126.276268,110.167313,105.155640,-741.101196,131.108948,98.712059,5.996109,106.587547,31.054474,-36.424126,25.684824,-103.723732,21.389105,57.723736,-672.727600,118.758759
2012-04-18 09:19:22.988281,118.937744,47.521400,301.147858,122.338524,62.556419,105.692604,-670.221802,135.404663,98.712059,3.848249,103.544746,32.665371,-34.455254,24.252918,-104.439690,19.599222,57.902725,-674.159546,117.505836
2012-04-18 09:19:22.992187,117.684822,50.743191,300.968872,102.291832,-23.894941,107.661476,-1065.070068,135.941635,99.070038,2.237354,104.976654,36.245136,-34.455254,21.926069,-104.439690,20.673151,59.513618,-676.486389,116.968872

In [14]:
cutoff_time_SE008 = pd.to_datetime("2012-04-18 03:21:21.000000")

In [15]:
SE008_a1_df = SE008_a1_df.loc[SE008_a1_df.index < cutoff_time_SE008]
print(SE008_a1_df.head(-1))

                               EEG Fp1    EEG Fp2      EEG F7      EEG F3  \
2012-04-17 17:02:08.000000  107.303505  78.486382  163.326843  136.478592
2012-04-17 17:02:08.003906  107.303505  78.665367  164.400772  136.120621
2012-04-17 17:02:08.007812  108.914398  80.634239  167.980545  138.626465
2012-04-17 17:02:08.011718  108.914398  80.992218  167.443573  138.805450
2012-04-17 17:02:08.015625  108.556419  81.529182  166.727631  137.552536
...                                ...        ...         ...         ...
2012-04-18 03:21:20.976562  149.186768  60.229572  223.466919  -24.968872
2012-04-18 03:21:20.980468  141.311279  55.754864  214.517517   -3.490272
2012-04-18 03:21:20.984375  128.961090  46.268482  201.630356   28.906614
2012-04-18 03:21:20.988281  130.571991  47.700390  203.420227   28.548637
2012-04-18 03:21:20.992187  143.459137  58.439690  216.844360   -3.669261

                                EEG Fz      EEG F4      EEG F8      EEG T3  \
2012-04-17 17:02:08.000000   -6.354085  123.591438  143.638138  102.649803
2012-04-17 17:02:08.003906   -6.354085  121.622566  142.922180  101.217896
2012-04-17 17:02:08.007812   -5.996109  123.412453  145.428009  103.723732
2012-04-17 17:02:08.011718   -5.459144  123.591438  146.143967  102.470818
2012-04-17 17:02:08.015625   -3.311284  124.486382  145.964981  101.575874
...                                ...         ...         ...         ...
2012-04-18 03:21:20.976562 -388.136200  105.871597   60.229572  110.346306
2012-04-18 03:21:20.980468  -44.120621   95.132294   55.217899  106.587547
2012-04-18 03:21:20.984375  369.521393   82.066147   45.731518   97.817123
2012-04-18 03:21:20.988281  296.852142   85.287941   45.552528   97.817123
2012-04-18 03:21:20.992187 -152.229568   99.964981   54.322956  105.513618

                               EEG C3     EEG Cz      EEG C4    EEG T4  \
2012-04-17 17:02:08.000000  41.435799  84.392998  104.797668 -5.280156
2012-04-17 17:02:08.003906  39.466927  81.350197  102.470818 -6.175097
2012-04-17 17:02:08.007812  39.824902  81.887161  104.081711 -4.922179
2012-04-17 17:02:08.011718  39.108948  82.424126  105.871597 -3.490272
2012-04-17 17:02:08.015625  38.929962  84.392998  107.661476 -1.342412
...                               ...        ...         ...       ...
2012-04-18 03:21:20.976562  40.898834  -5.101167  142.922180 -3.848249
2012-04-18 03:21:20.980468  38.750973  -8.680934  134.330734 -5.996109
2012-04-18 03:21:20.984375  32.665371 -15.124514  123.054474 -7.964981
2012-04-18 03:21:20.988281  30.696499 -17.630350  121.980545 -9.038911
2012-04-18 03:21:20.992187  34.992218 -15.124514  130.571991 -9.396887

                                EEG T5      EEG P3     EEG Pz     EEG P4  \
2012-04-17 17:02:08.000000  121.980545  138.805450  73.116730  30.338522
2012-04-17 17:02:08.003906  119.653694  135.225677  70.073929  28.011673
2012-04-17 17:02:08.007812  118.937744  135.762650  71.147858  28.190662
2012-04-17 17:02:08.011718  118.400780  136.120621  73.116730  30.159533
2012-04-17 17:02:08.015625  120.190659  137.731522  75.622566  32.844357
...                                ...         ...        ...        ...
2012-04-18 03:21:20.976562  171.202332  145.785995  77.770432  85.645912
2012-04-18 03:21:20.980468  168.338516  138.626465  70.252922  78.128403
2012-04-18 03:21:20.984375  157.778214  125.202332  57.723736  66.315178
2012-04-18 03:21:20.988281  155.630356  122.696495  53.428017  61.661480
2012-04-18 03:21:20.992187  164.400772  132.898834  58.976654  66.852142

                                EEG T6     EEG O1      EEG O2
2012-04-17 17:02:08.000000  -16.377432  63.988327  160.463028
2012-04-17 17:02:08.003906  -17.451363  61.482491  157.062256
2012-04-17 17:02:08.007812  -15.124514  59.513618  158.136185
2012-04-17 17:02:08.011718  -13.513618  58.439690  159.568100
2012-04-17 17:02:08.015625  -11.723736  60.229572  162.073929
...                                ...        ...         ...
2012-04-18 03:21:20.976562  134.867706  56.291828  260.517517
2012-04-18 03:21:20.980468  129.498047  61.482491  255.505844
2012-04-18 03:21:20.984375  117.863815  64.704277  244.050583
2012-04-18 03:21:20.988281  114.105057  60.050583  239.396881
2012-04-18 03:21:20.992187  120.369652  53.785992  246.377426

[9511167 rows x 19 columns]

`SE008_a1_df` went from [15010559 rows] to [9511167 rows]

##### Filter SE026_a1
by unique `cutoff_time_SE026`

In [16]:
SE026_a1_df = SE026_a1_df.copy()
SE026_a1_df.index = SE026_a1_df.index.tz_localize(None)

In [17]:
SE026_a1_df.head(-1)

,EEG Fp1,EEG Fp2,EEG F7,EEG F3,EEG Fz,EEG F4,EEG F8,EEG T3,EEG C3,EEG Cz,EEG C4,EEG T4,EEG T5,EEG P3,EEG Pz,EEG P4,EEG T6,EEG O1,EEG O2
2014-05-20 08:30:52.000000,-40.898834,92.089493,-12.260700,-146.143967,-72.937744,67.031128,166.190659,45.015564,-9.038911,69.536964,156.346298,130.750977,167.801559,206.284042,211.474701,176.214005,167.264587,162.968872,203.957199
2014-05-20 08:30:52.003906,-25.684824,102.649803,-12.439689,-136.657593,-37.319065,68.105057,165.832687,82.782104,-20.136187,86.898834,156.883270,130.035019,178.719849,205.926071,218.813232,201.809341,171.023346,167.085602,213.801559
2014-05-20 08:30:52.007812,-23.357977,103.365761,-9.038911,-129.319061,-34.813229,74.011673,168.875488,84.929962,-23.715954,82.245132,151.871597,132.361862,190.354080,207.178986,225.614792,210.221786,186.058365,178.182877,231.700394
2014-05-20 08:30:52.011718,-33.202335,95.669258,-4.206226,-132.182877,-68.642021,80.097275,177.108948,50.564201,-21.747082,58.976654,146.859924,140.595337,192.680939,206.821014,229.910507,196.618683,198.587555,193.396881,246.914398
2014-05-20 08:30:52.015625,-40.361866,92.984436,-1.879377,-139.163422,-91.552528,78.844360,183.731522,28.906614,-22.284046,44.836575,143.280151,141.490265,188.027237,202.525299,230.984436,180.867706,194.828796,198.945526,248.167313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-05-20 09:40:12.976562,-224.003891,-63.630352,-142.206223,-335.513611,-249.241241,-18.704281,58.439690,-104.260704,-292.198456,-219.708176,47.879379,7.785992,-73.474709,-156.704285,-200.556427,-34.455254,-24.252918,-117.326851,-135.404663
2014-05-20 09:40:12.980468,-227.941635,-70.252922,-157.778214,-337.303497,-251.031128,-14.408561,56.112839,-105.513618,-288.618683,-234.385208,40.182880,7.785992,-64.167313,-152.229568,-188.206223,-32.128407,-21.568094,-96.564201,-122.338524
2014-05-20 09:40:12.984375,-227.404663,-63.988327,-159.926071,-334.976654,-248.883270,-11.186770,59.334629,-103.186768,-284.501953,-234.206223,40.182880,9.575875,-62.019455,-149.365753,-181.762650,-29.801556,-19.778210,-89.941635,-116.610893
2014-05-20 09:40:12.988281,-224.361862,-55.038910,-147.217896,-330.859924,-246.735413,-14.229572,63.988327,-97.996109,-280.922180,-222.571991,44.657589,5.817121,-63.451363,-146.322952,-186.774323,-34.276264,-24.431906,-100.143967,-120.727623
2014-05-20 09:40:12.992187,-221.140076,-53.964981,-136.299606,-329.249023,-246.019455,-20.673151,67.210114,-94.416344,-276.268494,-215.770432,47.163425,2.416342,-64.525291,-142.564209,-190.891052,-42.330738,-29.264591,-108.377434,-124.128403

In [18]:
cutoff_time_SE026 = pd.to_datetime("2014-05-20 09:00:52.000000")

In [19]:
SE026_a1_df = SE026_a1_df.loc[SE026_a1_df.index < cutoff_time_SE026]
print(SE026_a1_df.head(-1))

                              EEG Fp1     EEG Fp2     EEG F7      EEG F3  \
2014-05-20 08:30:52.000000 -40.898834   92.089493 -12.260700 -146.143967
2014-05-20 08:30:52.003906 -25.684824  102.649803 -12.439689 -136.657593
2014-05-20 08:30:52.007812 -23.357977  103.365761  -9.038911 -129.319061
2014-05-20 08:30:52.011718 -33.202335   95.669258  -4.206226 -132.182877
2014-05-20 08:30:52.015625 -40.361866   92.984436  -1.879377 -139.163422
...                               ...         ...        ...         ...
2014-05-20 09:00:51.976562 -60.766537  -60.587547  10.112841   40.540855
2014-05-20 09:00:51.980468 -68.642021  -66.852142   6.712062   36.066147
2014-05-20 09:00:51.984375 -66.136185  -66.136185   7.249027   38.392998
2014-05-20 09:00:51.988281 -69.000000  -68.463036   4.922179   38.392998
2014-05-20 09:00:51.992187 -74.011673  -74.011673   2.237354   32.844357

                               EEG Fz     EEG F4      EEG F8     EEG T3  \
2014-05-20 08:30:52.000000 -72.937744  67.031128  166.190659  45.015564
2014-05-20 08:30:52.003906 -37.319065  68.105057  165.832687  82.782104
2014-05-20 08:30:52.007812 -34.813229  74.011673  168.875488  84.929962
2014-05-20 08:30:52.011718 -68.642021  80.097275  177.108948  50.564201
2014-05-20 08:30:52.015625 -91.552528  78.844360  183.731522  28.906614
...                               ...        ...         ...        ...
2014-05-20 09:00:51.976562  19.778210 -54.143970   21.031128  59.155643
2014-05-20 09:00:51.980468  11.723736 -55.217899   17.630350  38.214008
2014-05-20 09:00:51.984375   8.859922 -46.984436   19.420233  29.622568
2014-05-20 09:00:51.988281  10.291829 -50.922180   16.377432  35.350193
2014-05-20 09:00:51.992187  16.019455 -59.513618   11.007782  42.867702

                               EEG C3     EEG Cz      EEG C4      EEG T4  \
2014-05-20 08:30:52.000000  -9.038911  69.536964  156.346298  130.750977
2014-05-20 08:30:52.003906 -20.136187  86.898834  156.883270  130.035019
2014-05-20 08:30:52.007812 -23.715954  82.245132  151.871597  132.361862
2014-05-20 08:30:52.011718 -21.747082  58.976654  146.859924  140.595337
2014-05-20 08:30:52.015625 -22.284046  44.836575  143.280151  141.490265
...                               ...        ...         ...         ...
2014-05-20 09:00:51.976562  80.992218  69.357979   -0.089494  -34.634243
2014-05-20 09:00:51.980468  75.443581  59.155643   -2.237354  -36.782101
2014-05-20 09:00:51.984375  80.455254  55.754864    2.416342  -34.992218
2014-05-20 09:00:51.988281  85.466927  59.513618    3.490272  -36.424126
2014-05-20 09:00:51.992187  89.046692  66.494164    0.089494  -42.509727

                                EEG T5      EEG P3      EEG Pz      EEG P4  \
2014-05-20 08:30:52.000000  167.801559  206.284042  211.474701  176.214005
2014-05-20 08:30:52.003906  178.719849  205.926071  218.813232  201.809341
2014-05-20 08:30:52.007812  190.354080  207.178986  225.614792  210.221786
2014-05-20 08:30:52.011718  192.680939  206.821014  229.910507  196.618683
2014-05-20 08:30:52.015625  188.027237  202.525299  230.984436  180.867706
...                                ...         ...         ...         ...
2014-05-20 09:00:51.976562  -34.455254   11.007782   -5.996109  -39.645916
2014-05-20 09:00:51.980468  -37.856030    8.680934   -6.533074  -51.817120
2014-05-20 09:00:51.984375  -29.801556   16.377432    4.743191  -52.712063
2014-05-20 09:00:51.988281  -28.369650   21.210117    4.564202  -49.132298
2014-05-20 09:00:51.992187  -31.591440   21.568094   -5.280156  -47.879379

                                EEG T6      EEG O1      EEG O2
2014-05-20 08:30:52.000000  167.264587  162.968872  203.957199
2014-05-20 08:30:52.003906  171.023346  167.085602  213.801559
2014-05-20 08:30:52.007812  186.058365  178.182877  231.700394
2014-05-20 08:30:52.011718  198.587555  193.396881  246.914398
2014-05-20 08:30:52.015625  194.828796  198.945526  248.167313
...                                ...         ...         ...
2014-05-20 09:00:51.976562   20.673151  -23.894941   63.630352
2014-05-20 09:00:51.980468   14.229572  -22.821012   59.155643
2014-05-20 09:00:51.984375   14.408561   -6.533074   65.599220
2014-05-20 09:00:51.988281   11.365759   -3.132296   64.704277
2014-05-20 09:00:51.992187    4.564202   -8.322957   59.871593

[460799 rows x 19 columns]

`SE026_a1_df` went from [1065215 rows] to [460799 rows]

##### Filter SE038_a1
by unique `cutoff_time_SE038`

In [20]:
SE038_a1_df = SE038_a1_df.copy()
SE038_a1_df.index = SE038_a1_df.index.tz_localize(None)

In [21]:
SE038_a1_df.head(-1)

,EEG Fp1,EEG Fp2,EEG F7,EEG F3,EEG Fz,EEG F4,EEG F8,EEG T3,EEG C3,EEG Cz,EEG C4,EEG T4,EEG T5,EEG P3,EEG Pz,EEG P4,EEG T6,EEG O1,EEG O2
2018-05-23 11:05:57.000000,153.840469,-192.322952,-228.836578,49.311283,-100.680931,-157.599228,-234.743195,-129.856033,171.560318,-46.626461,-227.404663,-159.210114,-294.346313,-307.770416,-6.533074,-132.003891,-59.334629,-92.089493,28.548637
2018-05-23 11:05:57.003906,154.019455,-189.280151,-220.961090,45.910507,-101.933853,-163.326843,-230.626465,-135.046692,78.486382,-45.015564,-227.404663,-158.852142,-299.000000,-311.171204,-0.805447,-127.887161,-59.334629,-92.447472,39.287937
2018-05-23 11:05:57.007812,185.163422,-161.715958,-207.715958,91.910507,-82.066147,-130.571991,-210.042801,-120.369652,189.101166,-29.622568,-215.054474,-136.657593,-279.311279,-291.840454,7.249027,-118.400780,-38.214008,-82.066147,11.186770
2018-05-23 11:05:57.011718,200.556427,-150.797668,-209.505844,123.949417,-70.789886,-107.303505,-204.852142,-115.357979,361.287933,-22.463036,-208.073929,-127.529182,-273.583649,-283.964966,4.385214,-118.400780,-31.054474,-84.750977,-23.536964
2018-05-23 11:05:57.015625,178.540863,-171.381317,-228.120621,94.237350,-85.287941,-125.202332,-224.719849,-137.731522,364.509735,-33.381325,-216.486374,-147.933853,-298.821014,-308.128418,-9.754864,-131.466919,-51.996109,-107.303505,-23.357977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-05-23 12:50:31.976562,22.284046,-95.848251,-13.334630,-219.887161,-55.754864,33.202335,-37.856030,26.758755,-100.859924,-64.883270,-124.486382,-36.066147,-409.077820,-317.256805,-186.774323,-180.330734,-136.836578,-655.544739,-295.062256
2018-05-23 12:50:31.980468,22.105059,-89.941635,6.712062,-218.455246,-57.902725,34.634243,-46.805447,41.614784,-96.385216,-62.377434,-125.381325,-10.470818,-406.571991,-291.124512,-172.992218,-166.011673,-132.719849,-656.976624,-274.120636
2018-05-23 12:50:31.984375,21.210117,-79.560310,29.622568,-215.233459,-60.050583,36.424126,-47.521400,91.910507,-82.961090,-54.859921,-127.529182,-21.389105,-396.190674,-239.038910,-152.766541,-139.342407,-127.350197,-656.976624,-238.680939
2018-05-23 12:50:31.988281,23.536964,-87.614784,34.097275,-210.042801,-58.976654,39.645916,-44.657589,90.478600,-78.486382,-51.280155,-125.739296,-26.221790,-388.852142,-229.015564,-150.081711,-133.256805,-121.980545,-649.459167,-229.194550
2018-05-23 12:50:31.992187,33.918289,-93.521400,19.241245,-207.357971,-53.964981,40.540855,-36.245136,54.859921,-89.762650,-57.365757,-121.264595,-6.533074,-396.011688,-273.404663,-169.054474,-155.451355,-128.782104,-644.626465,-265.887146

In [22]:
cutoff_time_SE038 = pd.to_datetime("2018-05-23 11:36:27.000000")

In [23]:
SE038_a1_df = SE038_a1_df.loc[SE038_a1_df.index < cutoff_time_SE038]
print(SE038_a1_df.head(-1))

                               EEG Fp1     EEG Fp2      EEG F7      EEG F3  \
2018-05-23 11:05:57.000000  153.840469 -192.322952 -228.836578   49.311283
2018-05-23 11:05:57.003906  154.019455 -189.280151 -220.961090   45.910507
2018-05-23 11:05:57.007812  185.163422 -161.715958 -207.715958   91.910507
2018-05-23 11:05:57.011718  200.556427 -150.797668 -209.505844  123.949417
2018-05-23 11:05:57.015625  178.540863 -171.381317 -228.120621   94.237350
...                                ...         ...         ...         ...
2018-05-23 11:36:26.976562   46.984436  -35.350193  -50.564201   13.334630
2018-05-23 11:36:26.980468   40.361866  -33.202335  -24.610895    9.217898
2018-05-23 11:36:26.984375   34.276264  -31.591440   10.112841    7.964981
2018-05-23 11:36:26.988281   38.750973  -30.338522    8.322957    9.933852
2018-05-23 11:36:26.992187   48.237354  -29.443581  -26.579767   13.155642

                                EEG Fz      EEG F4      EEG F8      EEG T3  \
2018-05-23 11:05:57.000000 -100.680931 -157.599228 -234.743195 -129.856033
2018-05-23 11:05:57.003906 -101.933853 -163.326843 -230.626465 -135.046692
2018-05-23 11:05:57.007812  -82.066147 -130.571991 -210.042801 -120.369652
2018-05-23 11:05:57.011718  -70.789886 -107.303505 -204.852142 -115.357979
2018-05-23 11:05:57.015625  -85.287941 -125.202332 -224.719849 -137.731522
...                                ...         ...         ...         ...
2018-05-23 11:36:26.976562  -27.474709  -30.338522 -121.980545   48.237354
2018-05-23 11:36:26.980468  -33.381325  -33.381325 -128.424118   57.007782
2018-05-23 11:36:26.984375  -38.929962  -35.887161 -135.404663   66.852142
2018-05-23 11:36:26.988281  -35.529182  -33.560310 -131.824905   65.599220
2018-05-23 11:36:26.992187  -28.190662  -28.190662 -121.264595   55.038910

                                EEG C3     EEG Cz      EEG C4      EEG T4  \
2018-05-23 11:05:57.000000  171.560318 -46.626461 -227.404663 -159.210114
2018-05-23 11:05:57.003906   78.486382 -45.015564 -227.404663 -158.852142
2018-05-23 11:05:57.007812  189.101166 -29.622568 -215.054474 -136.657593
2018-05-23 11:05:57.011718  361.287933 -22.463036 -208.073929 -127.529182
2018-05-23 11:05:57.015625  364.509735 -33.381325 -216.486374 -147.933853
...                                ...        ...         ...         ...
2018-05-23 11:36:26.976562  -83.856033  53.964981 -121.085602 -122.159531
2018-05-23 11:36:26.980468  -80.455254  54.322956 -125.381325 -126.813232
2018-05-23 11:36:26.984375  -74.548637  55.933853 -130.035019 -133.077820
2018-05-23 11:36:26.988281  -74.369652  57.186771 -128.782104 -131.466919
2018-05-23 11:36:26.992187  -81.529182  55.038910 -123.591438 -124.665367

                                EEG T5      EEG P3     EEG Pz      EEG P4  \
2018-05-23 11:05:57.000000 -294.346313 -307.770416  -6.533074 -132.003891
2018-05-23 11:05:57.003906 -299.000000 -311.171204  -0.805447 -127.887161
2018-05-23 11:05:57.007812 -279.311279 -291.840454   7.249027 -118.400780
2018-05-23 11:05:57.011718 -273.583649 -283.964966   4.385214 -118.400780
2018-05-23 11:05:57.015625 -298.821014 -308.128418  -9.754864 -131.466919
...                                ...         ...        ...         ...
2018-05-23 11:36:26.976562    6.712062 -102.112839  -6.175097 -102.828796
2018-05-23 11:36:26.980468    9.217898  -94.416344   4.922179 -102.828796
2018-05-23 11:36:26.984375   14.050584  -87.435799  20.136187 -101.754868
2018-05-23 11:36:26.988281   14.766537  -89.762650  17.451363  -99.070038
2018-05-23 11:36:26.992187   11.723736  -97.996109   2.416342  -96.027237

                               EEG T6      EEG O1      EEG O2
2018-05-23 11:05:57.000000 -59.334629  -92.089493   28.548637
2018-05-23 11:05:57.003906 -59.334629  -92.447472   39.287937
2018-05-23 11:05:57.007812 -38.214008  -82.066147   11.186770
2018-05-23 11:05:57.011718 -31.054474  -84.750977  -23.536964
2018-05-23 11:05:57.015625 -51.996109 -107.303505  -23.357977
...                               ...         ...         ...
2018-05-23 11:36:26.976562 -60.229572   -2.416342   95.311287
2018-05-23 11:36:26.980468 -62.735409   -4.206226  120.011673
2018-05-23 11:36:26.984375 -65.778214   -6.533074  148.470810
2018-05-23 11:36:26.988281 -62.914398   -4.206226  145.607010
2018-05-23 11:36:26.992187 -56.470818    1.700389  115.715950

[468479 rows x 19 columns]

`SE038_a1_df` went from [1606399 rows] to [468479 rows]

#### Create Bipolar Channel Pairs

In [24]:
# create bipolar channels from the original channels
def create_bipolar_channels(df):
  """
  Creates bipolar channels from the original channels.

  Args:
    df: A Pandas DataFrame with the EEG data, where the index is a datetime object.

  Returns:
    A DataFrame with bipolar channels.
  """

  # create list of bipolar pairs
  bipolar_pairs = [
      ('Fp1-F7', 'EEG Fp1', 'EEG F7'),
      ('F7-T3', 'EEG F7', 'EEG T3'),
      ('T3-T5', 'EEG T3', 'EEG T5'),
      ('Fp1-F3', 'EEG Fp1', 'EEG F3'),
      ('F3-C3', 'EEG F3', 'EEG C3'),
      ('C3-P3', 'EEG C3', 'EEG P3'),
      ('P3-O1', 'EEG P3', 'EEG O1'),
      ('Fz-Cz', 'EEG Fz', 'EEG Cz'),
      ('Cz-Pz', 'EEG Cz', 'EEG Pz'),
      ('Fp2-F4', 'EEG Fp2', 'EEG F4'),
      ('F4-C4', 'EEG F4', 'EEG C4'),
      ('C4-P4', 'EEG C4', 'EEG P4'),
      ('P4-O2', 'EEG P4', 'EEG O2'),
      ('Fp2-F8', 'EEG Fp2', 'EEG F8'),
      ('F8-T4', 'EEG F8', 'EEG T4'),
      ('T4-T6', 'EEG T4', 'EEG T6'),
      ('T6-O2', 'EEG T6', 'EEG O2'),
  ]

  # create a new empty DataFrame
  bipolar_df = pd.DataFrame(index=df.index)

  for pair in bipolar_pairs:
      # strip any leading/trailing spaces from column names
      ch1 = pair[1].strip()  
      ch2 = pair[2].strip()

      if ch1 in df.columns and ch2 in df.columns:
          bipolar_df[pair[0]] = df[ch1] - df[ch2]
      else:
          print(f"Warning: Channel(s) missing for pair {pair[0]}")

  return bipolar_df

In [25]:
SE008_a1_df = create_bipolar_channels(SE008_a1_df)
SE021_a1_df = create_bipolar_channels(SE021_a1_df)
SE026_a1_df = create_bipolar_channels(SE026_a1_df)
SE038_a1_df = create_bipolar_channels(SE038_a1_df)

In [26]:
print(f"SE008_a1_df",SE008_a1_df.head())
print(f"SE021_a1_df",SE021_a1_df.head())
print(f"SE026_a1_df",SE026_a1_df.head())
print(f"SE038_a1_df",SE038_a1_df.head())

SE008_a1_df                                Fp1-F7      F7-T3      T3-T5     Fp1-F3  \
2012-04-17 17:02:08.000000 -56.023338  60.677040 -19.330742 -29.175087
2012-04-17 17:02:08.003906 -57.097267  63.182877 -18.435799 -28.817116
2012-04-17 17:02:08.007812 -59.066147  64.256813 -15.214012 -29.712067
2012-04-17 17:02:08.011718 -58.529175  64.972755 -15.929962 -29.891052
2012-04-17 17:02:08.015625 -58.171211  65.151756 -18.614784 -28.996117

                                F3-C3      C3-P3      P3-O1      Fz-Cz  \
2012-04-17 17:02:08.000000  95.042793 -97.369652  74.817123 -90.747086
2012-04-17 17:02:08.003906  96.653694 -95.758751  73.743187 -87.704285
2012-04-17 17:02:08.007812  98.801559 -95.937744  76.249031 -87.883270
2012-04-17 17:02:08.011718  99.696503 -97.011673  77.680931 -87.883270
2012-04-17 17:02:08.015625  98.622574 -98.801559  77.501953 -87.704285

                                Cz-Pz     Fp2-F4      F4-C4      C4-P4  \
2012-04-17 17:02:08.000000  11.276268 -45.105057  18.793770  74.459145
2012-04-17 17:02:08.003906  11.276268 -42.957199  19.151749  74.459145
2012-04-17 17:02:08.007812  10.739304 -42.778214  19.330742  75.891052
2012-04-17 17:02:08.011718   9.307396 -42.599220  17.719841  75.712067
2012-04-17 17:02:08.015625   8.770432 -42.957199  16.824905  74.817123

                                 P4-O2     Fp2-F8       F8-T4      T4-T6  \
2012-04-17 17:02:08.000000 -130.124512 -65.151756  148.918289  11.097277
2012-04-17 17:02:08.003906 -129.050583 -64.256813  149.097275  11.276265
2012-04-17 17:02:08.007812 -129.945526 -64.793770  150.350189  10.202334
2012-04-17 17:02:08.011718 -129.408569 -65.151749  149.634232  10.023346
2012-04-17 17:02:08.015625 -129.229568 -64.435799  147.307388  10.381323

                                 T6-O2
2012-04-17 17:02:08.000000 -176.840454
2012-04-17 17:02:08.003906 -174.513611
2012-04-17 17:02:08.007812 -173.260696
2012-04-17 17:02:08.011718 -173.081726
2012-04-17 17:02:08.015625 -173.797668
SE021_a1_df                                Fp1-F7      F7-T3      T3-T5      Fp1-F3  \
2015-09-01 16:06:27.000000  34.186771  62.287937 -63.898834  141.758759
2015-09-01 16:06:27.003906  35.260700  60.856033 -67.836578  140.863815
2015-09-01 16:06:27.007812  34.902725  59.066147 -69.626465  139.789886
2015-09-01 16:06:27.011718  35.260704  56.918289 -68.731522  138.536957
2015-09-01 16:06:27.015625  36.155640  56.202335 -65.509727  139.431915

                                 F3-C3       C3-P3      P3-O1       Fz-Cz  \
2015-09-01 16:06:27.000000 -108.645912  150.887161 -32.575874  141.937744
2015-09-01 16:06:27.003906 -109.361870  148.560303 -31.322960  138.536957
2015-09-01 16:06:27.007812 -110.077820  146.412445 -30.785988  138.000000
2015-09-01 16:06:27.011718 -109.540855  147.307404 -32.396889  137.821014
2015-09-01 16:06:27.015625 -108.287941  148.560303 -33.470818  138.536957

                                Cz-Pz      Fp2-F4      F4-C4      C4-P4  \
2015-09-01 16:06:27.000000 -18.972763  218.186768 -26.848248  28.459148
2015-09-01 16:06:27.003906 -25.953306  219.618683 -27.385212  23.626461
2015-09-01 16:06:27.007812 -28.459145  221.229568 -26.669258  20.941635
2015-09-01 16:06:27.011718 -23.805447  224.809341 -25.416340  20.225681
2015-09-01 16:06:27.015625 -16.108950  228.210114 -23.805450  19.688721

                                P4-O2     Fp2-F8      F8-T4       T4-T6  \
2015-09-01 16:06:27.000000 -39.735413  90.389099  97.190659  143.369644
2015-09-01 16:06:27.003906 -38.124519  90.210129  95.579765  142.832687
2015-09-01 16:06:27.007812 -39.556419  89.494164  96.653694  142.295715
2015-09-01 16:06:27.011718 -42.241245  92.357986  97.369652  141.221786
2015-09-01 16:06:27.015625 -43.852142  95.758759  96.832687  142.295715

                                 T6-O2
2015-09-01 16:06:27.000000 -150.887146
2015-09-01 16:06:27.003906 -150.887161
2015-09-01 16:06:27.007812 -152.498047
2015-09-01 16:06:27.011718 -153.571976
2015-09-01 16:06:27.015625 -154.645920
SE026_a1_df                                Fp1-F7      F7-T3       T3-T5      Fp1-F3  \
2014-05-20 08:30:52.000000 -28.638134 -57.276264 -122.785995  105.245132
2014-05-20 08:30:52.003906 -13.245135 -95.221794  -95.937744  110.972771
2014-05-20 08:30:52.007812 -14.319066 -93.968872 -105.424118  105.961082
2014-05-20 08:30:52.011718 -28.996109 -54.770428 -142.116730   98.980545
2014-05-20 08:30:52.015625 -38.482487 -30.785992 -159.120621   98.801559

                                 F3-C3       C3-P3      P3-O1       Fz-Cz  \
2014-05-20 08:30:52.000000 -137.105057 -215.322952  43.315170 -142.474701
2014-05-20 08:30:52.003906 -116.521408 -226.062256  38.840469 -124.217896
2014-05-20 08:30:52.007812 -105.603104 -230.894943  28.996109 -117.058365
2014-05-20 08:30:52.011718 -110.435791 -228.568100  13.424133 -127.618675
2014-05-20 08:30:52.015625 -116.879379 -224.809341   3.579773 -136.389099

                                 Cz-Pz     Fp2-F4      F4-C4      C4-P4  \
2014-05-20 08:30:52.000000 -141.937744  25.058365 -89.315170 -19.867706
2014-05-20 08:30:52.003906 -131.914398  34.544746 -88.778214 -44.926071
2014-05-20 08:30:52.007812 -143.369659  29.354088 -77.859924 -58.350189
2014-05-20 08:30:52.011718 -170.933853  15.571983 -66.762650 -49.758759
2014-05-20 08:30:52.015625 -186.147858  14.140076 -64.435791 -37.587555

                                P4-O2     Fp2-F8      F8-T4      T4-T6  \
2014-05-20 08:30:52.000000 -27.743195 -74.101166  35.439682 -36.513611
2014-05-20 08:30:52.003906 -11.992218 -63.182884  35.797668 -40.988327
2014-05-20 08:30:52.007812 -21.478607 -65.509727  36.513626 -53.696503
2014-05-20 08:30:52.011718 -50.295715 -81.439690  36.513611 -57.992218
2014-05-20 08:30:52.015625 -67.299606 -90.747086  42.241257 -53.338531

                                T6-O2
2014-05-20 08:30:52.000000 -36.692612
2014-05-20 08:30:52.003906 -42.778214
2014-05-20 08:30:52.007812 -45.642029
2014-05-20 08:30:52.011718 -48.326843
2014-05-20 08:30:52.015625 -53.338516
SE038_a1_df                                 Fp1-F7      F7-T3       T3-T5      Fp1-F3  \
2018-05-23 11:05:57.000000  382.677063 -98.980545  164.490280  104.529190
2018-05-23 11:05:57.003906  374.980530 -85.914398  163.953308  108.108948
2018-05-23 11:05:57.007812  392.879395 -87.346306  158.941620   93.252914
2018-05-23 11:05:57.011718  410.062256 -94.147865  158.225677   76.607010
2018-05-23 11:05:57.015625  406.661499 -90.389099  161.089493   84.303513

                                 F3-C3       C3-P3       P3-O1      Fz-Cz  \
2018-05-23 11:05:57.000000 -122.249039  479.330750 -215.680923 -54.054470
2018-05-23 11:05:57.003906  -32.575874  389.657593 -218.723724 -56.918289
2018-05-23 11:05:57.007812  -97.190659  480.941620 -209.774307 -52.443581
2018-05-23 11:05:57.011718 -237.338516  645.252930 -199.213989 -48.326851
2018-05-23 11:05:57.015625 -270.272400  672.638184 -200.824921 -51.906616

                                Cz-Pz     Fp2-F4       F4-C4      C4-P4  \
2018-05-23 11:05:57.000000 -40.093388 -34.723724   69.805435 -95.400772
2018-05-23 11:05:57.003906 -44.210117 -25.953308   64.077820 -99.517502
2018-05-23 11:05:57.007812 -36.871597 -31.143967   84.482483 -96.653694
2018-05-23 11:05:57.011718 -26.848249 -43.494164  100.770424 -89.673149
2018-05-23 11:05:57.015625 -23.626461 -46.178986   91.284042 -85.019455

                                 P4-O2     Fp2-F8      F8-T4      T4-T6  \
2018-05-23 11:05:57.000000 -160.552521  42.420242 -75.533081 -99.875488
2018-05-23 11:05:57.003906 -167.175095  41.346313 -71.774323 -99.517517
2018-05-23 11:05:57.007812 -129.587555  48.326843 -73.385208 -98.443588
2018-05-23 11:05:57.011718  -94.863815  54.054474 -77.322960 -96.474709
2018-05-23 11:05:57.015625 -108.108940  53.338531 -76.785995 -95.937744

                                T6-O2
2018-05-23 11:05:57.000000 -87.883270
2018-05-23 11:05:57.003906 -98.622566
2018-05-23 11:05:57.007812 -49.400780
2018-05-23 11:05:57.011718  -7.517509
2018-05-23 11:05:57.015625 -28.638132

In [27]:
print(SE008_a1_df.shape)
print(SE021_a1_df.shape)
print(SE026_a1_df.shape)
print(SE038_a1_df.shape)

(9511168, 17)
(368640, 17)
(460800, 17)
(468480, 17)

In [28]:
print(SE008_a1_df.info())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9511168 entries, 2012-04-17 17:02:08 to 2012-04-18 03:21:20.996093
Data columns (total 17 columns):
 #   Column  Dtype
---  ------  -----
 0   Fp1-F7  float32
 1   F7-T3   float32
 2   T3-T5   float32
 3   Fp1-F3  float32
 4   F3-C3   float32
 5   C3-P3   float32
 6   P3-O1   float32
 7   Fz-Cz   float32
 8   Cz-Pz   float32
 9   Fp2-F4  float32
 10  F4-C4   float32
 11  C4-P4   float32
 12  P4-O2   float32
 13  Fp2-F8  float32
 14  F8-T4   float32
 15  T4-T6   float32
 16  T6-O2   float32
dtypes: float32(17)
memory usage: 689.4 MB
None

#### Create Ground Truth Labels
Using `_annotations.txt` files for all patients

In [29]:
SE008_a1_annotations = pd.read_csv(RAW_KISPI_DATA_FOLDER / "SE008_annotated1_annotations.txt")
SE008_a1_annotations.head(-1)

                           Onset  Duration    Annotation
0    2012-04-17T17:02:12.5802030       NaN  Burst starts
1    2012-04-17T17:02:13.2416306       NaN     Burst end
2    2012-04-17T17:02:55.9220000       NaN  Burst starts
3    2012-04-17T17:02:57.5790000       NaN     Burst end
4    2012-04-17T17:03:00.5140000       NaN  Burst starts
..                           ...       ...           ...
286  2012-04-18T03:21:04.9590000       NaN  Burst starts
287  2012-04-18T03:21:05.9080000       NaN     Burst end
288  2012-04-18T03:21:08.9550000       NaN  Burst starts
289  2012-04-18T03:21:09.7740000       NaN     Burst end
290  2012-04-18T03:21:13.3084479       NaN  Burst starts

[291 rows x 3 columns]

In [30]:
SE008_a1_annotations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292 entries, 0 to 291
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Onset       292 non-null    object
 1   Duration    0 non-null      float64
 2   Annotation  292 non-null    object
dtypes: float64(1), object(2)
memory usage: 7.0+ KB

In [31]:
SE021_a1_annotations = pd.read_csv(RAW_KISPI_DATA_FOLDER / "SE021_annotated1_annotations.txt")
SE026_a1_annotations = pd.read_csv(RAW_KISPI_DATA_FOLDER / "SE026_annotated1_annotations.txt")
SE038_a1_annotations = pd.read_csv(RAW_KISPI_DATA_FOLDER / "SE038_annotated1_annotations.txt")

##### SE008_a1 Ground Truth Labels
Create `SE008_a1_ground_truth_df`

In [32]:
SE008_a1_df.head(-1)

,Fp1-F7,F7-T3,T3-T5,Fp1-F3,F3-C3,C3-P3,P3-O1,Fz-Cz,Cz-Pz,Fp2-F4,F4-C4,C4-P4,P4-O2,Fp2-F8,F8-T4,T4-T6,T6-O2
2012-04-17 17:02:08.000000,-56.023338,60.677040,-19.330742,-29.175087,95.042793,-97.369652,74.817123,-90.747086,11.276268,-45.105057,18.793770,74.459145,-130.124512,-65.151756,148.918289,11.097277,-176.840454
2012-04-17 17:02:08.003906,-57.097267,63.182877,-18.435799,-28.817116,96.653694,-95.758751,73.743187,-87.704285,11.276268,-42.957199,19.151749,74.459145,-129.050583,-64.256813,149.097275,11.276265,-174.513611
2012-04-17 17:02:08.007812,-59.066147,64.256813,-15.214012,-29.712067,98.801559,-95.937744,76.249031,-87.883270,10.739304,-42.778214,19.330742,75.891052,-129.945526,-64.793770,150.350189,10.202334,-173.260696
2012-04-17 17:02:08.011718,-58.529175,64.972755,-15.929962,-29.891052,99.696503,-97.011673,77.680931,-87.883270,9.307396,-42.599220,17.719841,75.712067,-129.408569,-65.151749,149.634232,10.023346,-173.081726
2012-04-17 17:02:08.015625,-58.171211,65.151756,-18.614784,-28.996117,98.622574,-98.801559,77.501953,-87.704285,8.770432,-42.957199,16.824905,74.817123,-129.229568,-64.435799,147.307388,10.381323,-173.797668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-04-18 03:21:20.976562,-74.280151,113.120613,-60.856026,174.155640,-65.867706,-104.887161,89.494171,-383.035034,-82.871597,-45.642025,-37.050583,57.276268,-174.871613,0.000000,64.077820,-138.715958,-125.649811
2012-04-18 03:21:20.980468,-73.206238,107.929970,-61.750969,144.801544,-42.241245,-99.875488,77.143974,-35.439686,-78.933853,-39.377430,-39.198441,56.202332,-177.377441,0.536964,61.214008,-135.494156,-126.007797
2012-04-18 03:21:20.984375,-72.669266,103.813232,-59.961090,100.054474,-3.758757,-92.536957,60.498055,384.645905,-72.848251,-35.797665,-40.988327,56.739296,-177.735413,0.536964,53.696499,-125.828796,-126.186768
2012-04-18 03:21:20.988281,-72.848236,105.603104,-57.813232,102.023354,-2.147861,-92.000000,62.645912,314.482483,-71.058365,-37.587551,-36.692604,60.319065,-177.735397,2.147861,54.591438,-123.143967,-125.291824
2012-04-18 03:21:20.992187,-73.385223,111.330742,-58.887154,147.128403,-38.661480,-97.906616,79.112839,-137.105057,-74.101166,-41.525291,-30.607010,63.719849,-179.525284,4.116734,63.719841,-129.766541,-126.007774

In [33]:
SE008_a1_annotations["Onset"] = pd.to_datetime(SE008_a1_annotations["Onset"], format="%Y-%m-%dT%H:%M:%S.%f")

SE008_a1_timestamps = SE008_a1_df.index
SE008_a1_ground_truth_df = pd.DataFrame(
    {"timestamp" : SE008_a1_timestamps, "ground_truth" : 0}
    )

SE008_a1_ground_truth_df["timestamp"] = pd.to_datetime(SE008_a1_ground_truth_df["timestamp"], format="%Y-%m-%dT%H:%M:%S.%f")

for index, row in SE008_a1_annotations.iterrows():
    if row["Annotation"] == "Burst starts":
        start_time = row["Onset"]
        try:
            # find the next row where the annotation is "Burst end"
            end_time = SE008_a1_annotations.loc[
                (SE008_a1_annotations["Annotation"] == "Burst end") &
                (SE008_a1_annotations.index > index), "Onset"
            ].iloc[0]
        
            SE008_a1_ground_truth_df.loc[
                (SE008_a1_ground_truth_df["timestamp"] >= start_time) 
                & (SE008_a1_ground_truth_df["timestamp"] <= end_time), 
                "ground_truth",] = 1
        except IndexError:
            print(f"Warning: No matching 'Burst end' annotation found for 'Burst starts' at {start_time}")

In [34]:
SE008_a1_ground_truth_df.head()

                   timestamp  ground_truth
0 2012-04-17 17:02:08.000000             0
1 2012-04-17 17:02:08.003906             0
2 2012-04-17 17:02:08.007812             0
3 2012-04-17 17:02:08.011718             0
4 2012-04-17 17:02:08.015625             0

In [35]:
print(SE008_a1_ground_truth_df.shape)
print(SE008_a1_df.shape)

(9511168, 2)
(9511168, 17)

In [36]:
SE008_a1_ground_truth_df.to_csv(
    RAW_KISPI_DATA_FOLDER / "SE008_a1_ground_truth.csv",
    date_format="%Y-%m-%d %H:%M:%S.%f"
)

##### SE021_a1 Ground Truth Labels
Create `SE021_a1_ground_truth_df`

In [37]:
SE021_a1_annotations.head(-1)

                           Onset  Duration   Annotation
0    2015-09-01T16:06:28.4270000       NaN  Burst start
1    2015-09-01T16:06:31.4130000       NaN    Burst end
2    2015-09-01T16:06:53.0490000       NaN  Burst start
3    2015-09-01T16:06:56.1850000       NaN    Burst end
4    2015-09-01T16:07:03.7870000       NaN  Burst start
..                           ...       ...          ...
100  2015-09-01T16:27:11.5340000       NaN  Burst start
101  2015-09-01T16:27:14.6310000       NaN    Burst end
102  2015-09-01T16:29:50.5230000       NaN  Burst start
103  2015-09-01T16:29:53.6010000       NaN    Burst end
104  2015-09-01T16:30:20.5160000       NaN  Burst start

[105 rows x 3 columns]

In [38]:
SE021_a1_df.index = SE021_a1_df.index.tz_localize(None)

In [39]:
SE021_a1_annotations["Onset"] = pd.to_datetime(SE021_a1_annotations["Onset"], format="%Y-%m-%dT%H:%M:%S.%f")

SE021_a1_timestamps = SE021_a1_df.index

SE021_a1_ground_truth_df = pd.DataFrame(
    {"timestamp" : SE021_a1_timestamps, "ground_truth" : 0}
)

SE021_a1_ground_truth_df["timestamp"] = pd.to_datetime(SE021_a1_ground_truth_df["timestamp"], format="%Y-%m-%dT%H:%M:%S.%f")

for index, row in SE021_a1_annotations.iterrows():
    if row["Annotation"] == "Burst start":
        start_time = row["Onset"]
        try:
            # find the next row where the annotation is "Burst end"
            end_time = SE021_a1_annotations.loc[
                (SE021_a1_annotations["Annotation"] == "Burst end") &
                (SE021_a1_annotations.index > index), "Onset"
            ].iloc[0]

            print(f"Labeling from {start_time} to {end_time}")  # Print the interval being labeled

            SE021_a1_ground_truth_df.loc[
                (SE021_a1_ground_truth_df["timestamp"] >= start_time)
                & (SE021_a1_ground_truth_df["timestamp"] <= end_time),
                "ground_truth",
            ] = 1
        except IndexError:
            print(f"Warning: No matching 'Burst end' annotation found for 'Burst start' at {start_time}")

Labeling from 2015-09-01 16:06:28.427000 to 2015-09-01 16:06:31.413000
Labeling from 2015-09-01 16:06:53.049000 to 2015-09-01 16:06:56.185000
Labeling from 2015-09-01 16:07:03.787000 to 2015-09-01 16:07:06.472000
Labeling from 2015-09-01 16:07:08.145000 to 2015-09-01 16:07:11.616000
Labeling from 2015-09-01 16:07:58.715000 to 2015-09-01 16:08:01.701000
Labeling from 2015-09-01 16:08:18.518000 to 2015-09-01 16:08:22.153000
Labeling from 2015-09-01 16:08:37.584000 to 2015-09-01 16:08:40.982000
Labeling from 2015-09-01 16:08:54.114000 to 2015-09-01 16:08:57.258000
Labeling from 2015-09-01 16:09:42.254000 to 2015-09-01 16:09:45.424000
Labeling from 2015-09-01 16:09:48.559000 to 2015-09-01 16:09:52.454000
Labeling from 2015-09-01 16:10:07.675000 to 2015-09-01 16:10:11.618000
Labeling from 2015-09-01 16:10:19.981000 to 2015-09-01 16:10:23.275000
Labeling from 2015-09-01 16:10:42.228000 to 2015-09-01 16:10:45.705000
Labeling from 2015-09-01 16:11:11.628000 to 2015-09-01 16:11:14.994000
Labeling from 2015-09-01 16:11:20.728000 to 2015-09-01 16:11:24.546000
Labeling from 2015-09-01 16:11:34.616000 to 2015-09-01 16:11:37.675000
Labeling from 2015-09-01 16:11:43.702000 to 2015-09-01 16:11:47.185000
Labeling from 2015-09-01 16:11:50.623000 to 2015-09-01 16:11:53.675000
Labeling from 2015-09-01 16:12:02.922000 to 2015-09-01 16:12:07.107000
Labeling from 2015-09-01 16:12:13.027000 to 2015-09-01 16:12:16.138000
Labeling from 2015-09-01 16:12:34.940000 to 2015-09-01 16:12:39.485000
Labeling from 2015-09-01 16:13:09.494000 to 2015-09-01 16:13:12.925000
Labeling from 2015-09-01 16:13:20.680000 to 2015-09-01 16:13:24.020000
Labeling from 2015-09-01 16:13:46.429000 to 2015-09-01 16:13:51.465000
Labeling from 2015-09-01 16:13:54.920000 to 2015-09-01 16:13:57.939000
Labeling from 2015-09-01 16:14:06.416000 to 2015-09-01 16:14:09.893000
Labeling from 2015-09-01 16:14:19.086000 to 2015-09-01 16:14:23.474000
Labeling from 2015-09-01 16:14:35.130000 to 2015-09-01 16:14:39.360000
Labeling from 2015-09-01 16:14:41.067000 to 2015-09-01 16:14:46.863000
Labeling from 2015-09-01 16:14:46.969000 to 2015-09-01 16:14:52.116000
Labeling from 2015-09-01 16:15:04.639000 to 2015-09-01 16:15:08.018000
Labeling from 2015-09-01 16:15:12.108000 to 2015-09-01 16:15:16.382000
Labeling from 2015-09-01 16:15:24.643000 to 2015-09-01 16:15:28.408000
Labeling from 2015-09-01 16:15:30.254000 to 2015-09-01 16:15:33.457000
Labeling from 2015-09-01 16:15:53.256000 to 2015-09-01 16:15:56.943000
Labeling from 2015-09-01 16:17:03.584000 to 2015-09-01 16:17:06.760000
Labeling from 2015-09-01 16:18:06.361000 to 2015-09-01 16:18:10.297000
Labeling from 2015-09-01 16:18:31.564000 to 2015-09-01 16:18:35.703000
Labeling from 2015-09-01 16:18:37.597000 to 2015-09-01 16:18:41.716000
Labeling from 2015-09-01 16:20:02.715000 to 2015-09-01 16:20:06.644000
Labeling from 2015-09-01 16:20:23.916000 to 2015-09-01 16:20:27.334000
Labeling from 2015-09-01 16:21:42.911000 to 2015-09-01 16:21:46.028000
Labeling from 2015-09-01 16:21:47.713000 to 2015-09-01 16:21:50.745000
Labeling from 2015-09-01 16:22:34.415000 to 2015-09-01 16:22:37.775000
Labeling from 2015-09-01 16:22:41.859000 to 2015-09-01 16:22:45.428000
Labeling from 2015-09-01 16:24:11.819000 to 2015-09-01 16:24:15.618000
Labeling from 2015-09-01 16:24:46.787000 to 2015-09-01 16:24:50.087000
Labeling from 2015-09-01 16:25:19.664000 to 2015-09-01 16:25:22.709000
Labeling from 2015-09-01 16:26:04.621000 to 2015-09-01 16:26:07.424000
Labeling from 2015-09-01 16:26:11.824000 to 2015-09-01 16:26:15.845000
Labeling from 2015-09-01 16:27:11.534000 to 2015-09-01 16:27:14.631000
Labeling from 2015-09-01 16:29:50.523000 to 2015-09-01 16:29:53.601000
Labeling from 2015-09-01 16:30:20.516000 to 2015-09-01 16:30:24.098000

In [40]:
SE021_a1_ground_truth_df.head(-1)

                        timestamp  ground_truth
0      2015-09-01 16:06:27.000000             0
1      2015-09-01 16:06:27.003906             0
2      2015-09-01 16:06:27.007812             0
3      2015-09-01 16:06:27.011718             0
4      2015-09-01 16:06:27.015625             0
...                           ...           ...
368634 2015-09-01 16:30:26.976562             0
368635 2015-09-01 16:30:26.980468             0
368636 2015-09-01 16:30:26.984375             0
368637 2015-09-01 16:30:26.988281             0
368638 2015-09-01 16:30:26.992187             0

[368639 rows x 2 columns]

In [41]:
print(SE021_a1_ground_truth_df.shape)
print(SE021_a1_df.shape)

(368640, 2)
(368640, 17)

In [42]:
SE021_a1_ground_truth_df.to_csv(
    RAW_KISPI_DATA_FOLDER / "SE021_a1_ground_truth.csv",
    date_format="%Y-%m-%d %H:%M:%S.%f")

##### SE026_a1 Ground Truth Labels
Create `SE026_a1_ground_truth_df`

In [43]:
SE026_a1_annotations

                           Onset  Duration Annotation
0    2014-05-20T08:30:58.0110000       NaN      burst
1    2014-05-20T08:31:00.6570000       NaN      burst
2    2014-05-20T08:32:33.7090000       NaN      burst
3    2014-05-20T08:32:34.7430000       NaN      burst
4    2014-05-20T08:33:49.7850000       NaN      burst
..                           ...       ...        ...
131  2014-05-20T08:53:41.0400000       NaN      burst
132  2014-05-20T08:54:40.9620000       NaN      burst
133  2014-05-20T08:54:41.9700000       NaN      burst
134  2014-05-20T08:55:11.9350000       NaN      burst
135  2014-05-20T08:55:12.9370000       NaN      burst

[136 rows x 3 columns]

In [44]:
SE026_a1_annotations["Onset"] = pd.to_datetime(SE026_a1_annotations["Onset"], format="%Y-%m-%dT%H:%M:%S.%f")

SE026_a1_timestamps = SE026_a1_df.index

SE026_a1_ground_truth_df = pd.DataFrame(
    {"timestamp" : SE026_a1_timestamps, "ground_truth" : 0}
    )

SE026_a1_ground_truth_df["timestamp"] = pd.to_datetime(SE026_a1_ground_truth_df["timestamp"], format="%Y-%m-%dT%H:%M:%S.%f")

burst_count = 0
for index, row in SE026_a1_annotations.iterrows():
    if row["Annotation"] == "burst":
        burst_count += 1
        if burst_count % 2 == 0:  # Check if it's an even count (should be a closing 'burst')
            end_time = row["Onset"]

            print(f"Labeling from {start_time} to {end_time}")
            
            SE026_a1_ground_truth_df.loc[
                (SE026_a1_ground_truth_df["timestamp"] >= start_time)
                & (SE026_a1_ground_truth_df["timestamp"] <= end_time),
                "ground_truth",] = 1
        else:
            start_time = row["Onset"]

if burst_count % 2 != 0:
    print(f"Warning: Unclosed 'burst' at {start_time}")

Labeling from 2014-05-20 08:30:58.011000 to 2014-05-20 08:31:00.657000
Labeling from 2014-05-20 08:32:33.709000 to 2014-05-20 08:32:34.743000
Labeling from 2014-05-20 08:33:49.785000 to 2014-05-20 08:33:50.518000
Labeling from 2014-05-20 08:35:14.392000 to 2014-05-20 08:35:15.394000
Labeling from 2014-05-20 08:35:29.195000 to 2014-05-20 08:35:30.060000
Labeling from 2014-05-20 08:35:40.261000 to 2014-05-20 08:35:41.315000
Labeling from 2014-05-20 08:36:01.547000 to 2014-05-20 08:36:02.359000
Labeling from 2014-05-20 08:36:07.975000 to 2014-05-20 08:36:08.741000
Labeling from 2014-05-20 08:36:15.407000 to 2014-05-20 08:36:16.173000
Labeling from 2014-05-20 08:36:20.749000 to 2014-05-20 08:36:21.535000
Labeling from 2014-05-20 08:36:23.599000 to 2014-05-20 08:36:24.588000
Labeling from 2014-05-20 08:36:35.538000 to 2014-05-20 08:36:36.756000
Labeling from 2014-05-20 08:36:44.038000 to 2014-05-20 08:36:45.119000
Labeling from 2014-05-20 08:36:58.444000 to 2014-05-20 08:37:00.049000
Labeling from 2014-05-20 08:37:07.507000 to 2014-05-20 08:37:08.594000
Labeling from 2014-05-20 08:37:45.575000 to 2014-05-20 08:37:46.918000
Labeling from 2014-05-20 08:38:10.429000 to 2014-05-20 08:38:11.896000
Labeling from 2014-05-20 08:38:18.079000 to 2014-05-20 08:38:18.957000
Labeling from 2014-05-20 08:38:36.704000 to 2014-05-20 08:38:37.621000
Labeling from 2014-05-20 08:39:15.223000 to 2014-05-20 08:39:16.140000
Labeling from 2014-05-20 08:39:25.276000 to 2014-05-20 08:39:26.108000
Labeling from 2014-05-20 08:39:32.608000 to 2014-05-20 08:39:33.551000
Labeling from 2014-05-20 08:39:41.844000 to 2014-05-20 08:39:42.715000
Labeling from 2014-05-20 08:40:39.979000 to 2014-05-20 08:40:41.106000
Labeling from 2014-05-20 08:41:21.254000 to 2014-05-20 08:41:22.433000
Labeling from 2014-05-20 08:41:29.195000 to 2014-05-20 08:41:30.099000
Labeling from 2014-05-20 08:41:51.732000 to 2014-05-20 08:41:53.036000
Labeling from 2014-05-20 08:42:00.038000 to 2014-05-20 08:42:01.171000
Labeling from 2014-05-20 08:42:11.544000 to 2014-05-20 08:42:12.363000
Labeling from 2014-05-20 08:42:29.593000 to 2014-05-20 08:42:30.654000
Labeling from 2014-05-20 08:42:48.715000 to 2014-05-20 08:42:49.618000
Labeling from 2014-05-20 08:43:20.920000 to 2014-05-20 08:43:22.728000
Labeling from 2014-05-20 08:43:27.464000 to 2014-05-20 08:43:28.368000
Labeling from 2014-05-20 08:43:36.047000 to 2014-05-20 08:43:37.311000
Labeling from 2014-05-20 08:44:25.809000 to 2014-05-20 08:44:26.935000
Labeling from 2014-05-20 08:44:40.130000 to 2014-05-20 08:44:41.269000
Labeling from 2014-05-20 08:44:56.693000 to 2014-05-20 08:44:57.472000
Labeling from 2014-05-20 08:45:11.815000 to 2014-05-20 08:45:13.125000
Labeling from 2014-05-20 08:45:48.481000 to 2014-05-20 08:45:49.673000
Labeling from 2014-05-20 08:45:54.320000 to 2014-05-20 08:45:56.383000
Labeling from 2014-05-20 08:46:21.161000 to 2014-05-20 08:46:22.739000
Labeling from 2014-05-20 08:46:50.425000 to 2014-05-20 08:46:51.728000
Labeling from 2014-05-20 08:46:56.693000 to 2014-05-20 08:46:57.688000
Labeling from 2014-05-20 08:47:02.695000 to 2014-05-20 08:47:03.684000
Labeling from 2014-05-20 08:47:08.160000 to 2014-05-20 08:47:09.175000
Labeling from 2014-05-20 08:47:38.012000 to 2014-05-20 08:47:39.616000
Labeling from 2014-05-20 08:47:56.621000 to 2014-05-20 08:47:57.603000
Labeling from 2014-05-20 08:48:03.831000 to 2014-05-20 08:48:04.898000
Labeling from 2014-05-20 08:48:08.626000 to 2014-05-20 08:48:10.950000
Labeling from 2014-05-20 08:48:52.984000 to 2014-05-20 08:48:54.444000
Labeling from 2014-05-20 08:49:07.730000 to 2014-05-20 08:49:08.929000
Labeling from 2014-05-20 08:49:14.960000 to 2014-05-20 08:49:15.994000
Labeling from 2014-05-20 08:49:19.846000 to 2014-05-20 08:49:22.531000
Labeling from 2014-05-20 08:50:01.457000 to 2014-05-20 08:50:02.859000
Labeling from 2014-05-20 08:50:15.819000 to 2014-05-20 08:50:17.227000
Labeling from 2014-05-20 08:50:28.051000 to 2014-05-20 08:50:29.656000
Labeling from 2014-05-20 08:50:33.062000 to 2014-05-20 08:50:36.160000
Labeling from 2014-05-20 08:50:49.001000 to 2014-05-20 08:50:50.166000
Labeling from 2014-05-20 08:50:58.435000 to 2014-05-20 08:50:59.522000
Labeling from 2014-05-20 08:51:04.294000 to 2014-05-20 08:51:05.485000
Labeling from 2014-05-20 08:51:51.354000 to 2014-05-20 08:51:53.018000
Labeling from 2014-05-20 08:52:06.903000 to 2014-05-20 08:52:08.566000
Labeling from 2014-05-20 08:52:23.942000 to 2014-05-20 08:52:24.905000
Labeling from 2014-05-20 08:53:03.835000 to 2014-05-20 08:53:05.361000
Labeling from 2014-05-20 08:53:17.916000 to 2014-05-20 08:53:19.448000
Labeling from 2014-05-20 08:53:38.899000 to 2014-05-20 08:53:41.040000
Labeling from 2014-05-20 08:54:40.962000 to 2014-05-20 08:54:41.970000
Labeling from 2014-05-20 08:55:11.935000 to 2014-05-20 08:55:12.937000

In [45]:
SE026_a1_ground_truth_df.head()

                   timestamp  ground_truth
0 2014-05-20 08:30:52.000000             0
1 2014-05-20 08:30:52.003906             0
2 2014-05-20 08:30:52.007812             0
3 2014-05-20 08:30:52.011718             0
4 2014-05-20 08:30:52.015625             0

In [46]:
print(SE026_a1_ground_truth_df.shape)
print(SE026_a1_df.shape)

(460800, 2)
(460800, 17)

In [47]:
SE026_a1_ground_truth_df.to_csv(
    RAW_KISPI_DATA_FOLDER / "SE026_a1_ground_truth.csv",
    date_format="%Y-%m-%d %H:%M:%S.%f")

##### SE038_a1 Ground Truth Labels
Create `SE038_a1_ground_truth_df`

In [48]:
SE038_a1_annotations.head(-1)

                           Onset  Duration    Annotation
0    2018-05-23T11:06:21.1931892       NaN  burst starts
1    2018-05-23T11:06:21.7105435       NaN     burst end
2    2018-05-23T11:06:27.8244924       NaN  burst starts
3    2018-05-23T11:06:28.3491617       NaN     burst end
4    2018-05-23T11:06:31.0341650       NaN  burst starts
..                           ...       ...           ...
465  2018-05-23T11:36:14.6200000       NaN         burst
466  2018-05-23T11:36:15.4190000       NaN         burst
467  2018-05-23T11:36:18.5560000       NaN         burst
468  2018-05-23T11:36:19.1320000       NaN         burst
469  2018-05-23T11:36:23.8330000       NaN         burst

[470 rows x 3 columns]

In [49]:
SE038_a1_annotations.iloc[158:182]

                           Onset  Duration    Annotation
158  2018-05-23T11:13:38.8137819       NaN  burst starts
159  2018-05-23T11:13:39.1010000       NaN     burst end
160  2018-05-23T11:13:43.0060000     0.858         burst
161  2018-05-23T11:13:47.7210000     0.590         burst
162  2018-05-23T11:17:48.8244950     0.590         burst
163  2018-05-23T11:17:54.6860000     0.551         burst
164  2018-05-23T11:17:55.2420000     0.551         burst
165  2018-05-23T11:17:57.3640000     0.551         burst
166  2018-05-23T11:18:01.8100000     0.551         burst
167  2018-05-23T11:18:02.3600000     0.551         burst
168  2018-05-23T11:18:06.2680000     0.551         burst
169  2018-05-23T11:18:06.9100000     0.551         burst
170  2018-05-23T11:18:18.1290000     0.551         burst
171  2018-05-23T11:18:18.7050000     0.551         burst
172  2018-05-23T11:18:21.9930000     0.551         burst
173  2018-05-23T11:18:22.5560000     0.551         burst
174  2018-05-23T11:18:26.8420000     0.551         burst
175  2018-05-23T11:18:27.3990000     0.551         burst
176  2018-05-23T11:18:33.7580000     0.551         burst
177  2018-05-23T11:18:34.2560000     0.551         burst
178  2018-05-23T11:18:37.4470000     0.551         burst
179  2018-05-23T11:18:38.0040000     0.551         burst
180  2018-05-23T11:18:40.7680000     0.551         burst
181  2018-05-23T11:18:46.0180000       NaN  burst starts

In [50]:
SE038_a1_annotations["Onset"] = pd.to_datetime(SE038_a1_annotations["Onset"], format="%Y-%m-%dT%H:%M:%S.%f")

SE038_a1_timestamps = SE038_a1_df.index

SE038_a1_ground_truth_df = pd.DataFrame(
    {"timestamp" : SE038_a1_timestamps, "ground_truth" : 0}
)

SE038_a1_ground_truth_df["timestamp"] = pd.to_datetime(SE038_a1_ground_truth_df["timestamp"], format="%Y-%m-%dT%H:%M:%S.%f")

# Handling "burst-starts" and "burst-end" pairs
start_time = None
burst_start_count = 0
burst_end_count = 0
for index, row in SE038_a1_annotations.iterrows():
    if row["Annotation"] == "burst starts":
        burst_start_count += 1
        if start_time is None:
            start_time = row["Onset"]
        else:
            print(f"Warning: Unexpected 'burst starts' at {row['Onset']} without a matching 'burst end'")
    elif row["Annotation"] == "burst end":
        burst_end_count += 1
        if start_time is not None:
            end_time = row["Onset"]

            print(f"Labeling from {start_time} to {end_time}")

            SE038_a1_ground_truth_df.loc[
                (SE038_a1_ground_truth_df["timestamp"] >= start_time)
                & (SE038_a1_ground_truth_df["timestamp"] <= end_time),
                "ground_truth",
            ] = 1
            start_time = None  # Reset start_time for the next pair
        else:
            print(f"Warning: Unexpected 'burst end' at {row['Onset']} without a matching 'burst starts'")

if start_time is not None:
    print(f"Warning: Unclosed 'burst starts' at {start_time}")

if burst_start_count == burst_end_count:
    print("'burst-starts' and 'burst-end' pairs are even")
else:
    print(f"Warning: Uneven number of 'burst-starts' ({burst_start_count}) and 'burst-end' ({burst_end_count}) annotations")

# Handling simple "burst" with duration
for index, row in SE038_a1_annotations.iterrows():
    if row["Annotation"] == "burst" and pd.notna(row["Duration"]):
        start_time = row["Onset"]
        end_time = start_time + pd.to_timedelta(row["Duration"], unit='s')  # Calculate end_time using duration
        
        print(f"Labeling from {start_time} to {end_time}")  # Optional: Print the interval being labeled

        SE038_a1_ground_truth_df.loc[
            (SE038_a1_ground_truth_df["timestamp"] >= start_time)
            & (SE038_a1_ground_truth_df["timestamp"] <= end_time),
            "ground_truth",
        ] = 1

Labeling from 2018-05-23 11:06:21.193189200 to 2018-05-23 11:06:21.710543500
Labeling from 2018-05-23 11:06:27.824492400 to 2018-05-23 11:06:28.349161700
Labeling from 2018-05-23 11:06:31.034165 to 2018-05-23 11:06:31.649751100
Labeling from 2018-05-23 11:06:38.055432200 to 2018-05-23 11:06:38.635998600
Labeling from 2018-05-23 11:06:42.714895100 to 2018-05-23 11:06:43.124194400
Labeling from 2018-05-23 11:06:49.029000 to 2018-05-23 11:06:49.370000
Labeling from 2018-05-23 11:06:53.322000 to 2018-05-23 11:06:53.761000
Labeling from 2018-05-23 11:06:58.492000 to 2018-05-23 11:06:58.898000
Labeling from 2018-05-23 11:07:02.805000 to 2018-05-23 11:07:03.296000
Labeling from 2018-05-23 11:07:06.726000 to 2018-05-23 11:07:07.270000
Labeling from 2018-05-23 11:07:10.401000 to 2018-05-23 11:07:10.918000
Labeling from 2018-05-23 11:07:15.754000 to 2018-05-23 11:07:16.219000
Labeling from 2018-05-23 11:07:21.711000 to 2018-05-23 11:07:22.314000
Labeling from 2018-05-23 11:07:27.556000 to 2018-05-23 11:07:28.126000
Labeling from 2018-05-23 11:08:09.395000 to 2018-05-23 11:08:09.965000
Labeling from 2018-05-23 11:08:18.980000 to 2018-05-23 11:08:19.412000
Labeling from 2018-05-23 11:08:24.084000 to 2018-05-23 11:08:24.523000
Labeling from 2018-05-23 11:08:30.720000 to 2018-05-23 11:08:31.250000
Labeling from 2018-05-23 11:08:35.798000 to 2018-05-23 11:08:36.355000
Labeling from 2018-05-23 11:08:41.576000 to 2018-05-23 11:08:42.034000
Labeling from 2018-05-23 11:08:46.185000 to 2018-05-23 11:08:46.669000
Labeling from 2018-05-23 11:08:50.318000 to 2018-05-23 11:08:50.789000
Labeling from 2018-05-23 11:08:54.905000 to 2018-05-23 11:08:55.318000
Labeling from 2018-05-23 11:09:00.770000 to 2018-05-23 11:09:01.196000
Labeling from 2018-05-23 11:09:05.359000 to 2018-05-23 11:09:05.818000
Labeling from 2018-05-23 11:09:10.523000 to 2018-05-23 11:09:10.929000
Labeling from 2018-05-23 11:09:12.988634500 to 2018-05-23 11:09:13.420854500
Labeling from 2018-05-23 11:09:16.049000 to 2018-05-23 11:09:16.481000
Labeling from 2018-05-23 11:09:22.525000 to 2018-05-23 11:09:22.964000
Labeling from 2018-05-23 11:09:28.198000 to 2018-05-23 11:09:28.604000
Labeling from 2018-05-23 11:09:32.185000 to 2018-05-23 11:09:32.754000
Labeling from 2018-05-23 11:09:42.940000 to 2018-05-23 11:09:43.268000
Labeling from 2018-05-23 11:09:46.639000 to 2018-05-23 11:09:47.091000
Labeling from 2018-05-23 11:09:52.986000 to 2018-05-23 11:09:53.314000
Labeling from 2018-05-23 11:09:58.940000 to 2018-05-23 11:09:59.294000
Labeling from 2018-05-23 11:10:05.346000 to 2018-05-23 11:10:05.692629300
Labeling from 2018-05-23 11:10:09.595707200 to 2018-05-23 11:10:10.060671200
Labeling from 2018-05-23 11:10:13.278000 to 2018-05-23 11:10:13.619000
Labeling from 2018-05-23 11:10:17.219000 to 2018-05-23 11:10:17.462000
Labeling from 2018-05-23 11:10:20.957000 to 2018-05-23 11:10:21.246000
Labeling from 2018-05-23 11:10:23.800000 to 2018-05-23 11:10:24.101000
Labeling from 2018-05-23 11:10:29.141000 to 2018-05-23 11:10:29.501000
Labeling from 2018-05-23 11:10:32.375000 to 2018-05-23 11:10:32.728000
Labeling from 2018-05-23 11:10:36.080000 to 2018-05-23 11:10:36.388000
Labeling from 2018-05-23 11:10:41.427000 to 2018-05-23 11:10:41.898000
Labeling from 2018-05-23 11:10:46.132000 to 2018-05-23 11:10:46.433000
Labeling from 2018-05-23 11:10:50.309000 to 2018-05-23 11:10:50.761000
Labeling from 2018-05-23 11:10:54.912000 to 2018-05-23 11:10:55.259000
Labeling from 2018-05-23 11:10:59.388000 to 2018-05-23 11:10:59.813000
Labeling from 2018-05-23 11:11:03.591000 to 2018-05-23 11:11:03.970000
Labeling from 2018-05-23 11:11:09.486000 to 2018-05-23 11:11:09.925000
Labeling from 2018-05-23 11:11:14.591000 to 2018-05-23 11:11:14.984000
Labeling from 2018-05-23 11:11:28.440000 to 2018-05-23 11:11:28.853000
Labeling from 2018-05-23 11:11:32.853000 to 2018-05-23 11:11:33.160000
Labeling from 2018-05-23 11:11:38.069000 to 2018-05-23 11:11:38.442000
Labeling from 2018-05-23 11:11:43.008000 to 2018-05-23 11:11:43.427000
Labeling from 2018-05-23 11:11:47.964000 to 2018-05-23 11:11:48.291000
Labeling from 2018-05-23 11:11:52.650000 to 2018-05-23 11:11:53.252000
Labeling from 2018-05-23 11:11:56.794000 to 2018-05-23 11:11:57.160000
Labeling from 2018-05-23 11:12:00.892000 to 2018-05-23 11:12:01.383000
Labeling from 2018-05-23 11:12:06.885000 to 2018-05-23 11:12:07.304000
Labeling from 2018-05-23 11:12:12.422000 to 2018-05-23 11:12:12.861000
Labeling from 2018-05-23 11:12:16.036000 to 2018-05-23 11:12:16.481000
Labeling from 2018-05-23 11:12:24.514000 to 2018-05-23 11:12:24.894000
Labeling from 2018-05-23 11:12:27.993000 to 2018-05-23 11:12:28.392000
Labeling from 2018-05-23 11:12:31.263000 to 2018-05-23 11:12:31.610000
Labeling from 2018-05-23 11:12:36.656000 to 2018-05-23 11:12:36.951000
Labeling from 2018-05-23 11:12:40.951000 to 2018-05-23 11:12:41.383000
Labeling from 2018-05-23 11:12:45.846000 to 2018-05-23 11:12:46.272851900
Labeling from 2018-05-23 11:12:49.246001900 to 2018-05-23 11:12:49.638000
Labeling from 2018-05-23 11:12:53.772000 to 2018-05-23 11:12:54.113000
Labeling from 2018-05-23 11:12:59.230000 to 2018-05-23 11:12:59.630000
Labeling from 2018-05-23 11:13:04.250000 to 2018-05-23 11:13:04.663000
Labeling from 2018-05-23 11:13:07.905000 to 2018-05-23 11:13:08.193000
Labeling from 2018-05-23 11:13:13.318000 to 2018-05-23 11:13:13.638000
Labeling from 2018-05-23 11:13:23.108000 to 2018-05-23 11:13:23.455000
Labeling from 2018-05-23 11:13:27.237000 to 2018-05-23 11:13:27.623000
Labeling from 2018-05-23 11:13:34.453000 to 2018-05-23 11:13:34.707691500
Labeling from 2018-05-23 11:13:38.813781900 to 2018-05-23 11:13:39.101000
Labeling from 2018-05-23 11:18:46.018000 to 2018-05-23 11:18:46.542000
Labeling from 2018-05-23 11:18:51.998000 to 2018-05-23 11:18:52.502000
Labeling from 2018-05-23 11:18:55.585000 to 2018-05-23 11:18:56.109000
Labeling from 2018-05-23 11:19:01.231000 to 2018-05-23 11:19:01.873000
Labeling from 2018-05-23 11:19:04.866000 to 2018-05-23 11:19:05.351000
Labeling from 2018-05-23 11:19:09.460000 to 2018-05-23 11:19:09.969000
Labeling from 2018-05-23 11:19:15.035000 to 2018-05-23 11:19:15.539000
Labeling from 2018-05-23 11:19:20.192000 to 2018-05-23 11:19:20.690000
'burst-starts' and 'burst-end' pairs are even
Labeling from 2018-05-23 11:07:43.193000 to 2018-05-23 11:07:43.789000
Labeling from 2018-05-23 11:07:47.682000 to 2018-05-23 11:07:48.370000
Labeling from 2018-05-23 11:13:43.006000 to 2018-05-23 11:13:43.864000
Labeling from 2018-05-23 11:13:47.721000 to 2018-05-23 11:13:48.311000
Labeling from 2018-05-23 11:17:48.824495 to 2018-05-23 11:17:49.414495
Labeling from 2018-05-23 11:17:54.686000 to 2018-05-23 11:17:55.237000
Labeling from 2018-05-23 11:17:55.242000 to 2018-05-23 11:17:55.793000
Labeling from 2018-05-23 11:17:57.364000 to 2018-05-23 11:17:57.915000
Labeling from 2018-05-23 11:18:01.810000 to 2018-05-23 11:18:02.361000
Labeling from 2018-05-23 11:18:02.360000 to 2018-05-23 11:18:02.911000
Labeling from 2018-05-23 11:18:06.268000 to 2018-05-23 11:18:06.819000
Labeling from 2018-05-23 11:18:06.910000 to 2018-05-23 11:18:07.461000
Labeling from 2018-05-23 11:18:18.129000 to 2018-05-23 11:18:18.680000
Labeling from 2018-05-23 11:18:18.705000 to 2018-05-23 11:18:19.256000
Labeling from 2018-05-23 11:18:21.993000 to 2018-05-23 11:18:22.544000
Labeling from 2018-05-23 11:18:22.556000 to 2018-05-23 11:18:23.107000
Labeling from 2018-05-23 11:18:26.842000 to 2018-05-23 11:18:27.393000
Labeling from 2018-05-23 11:18:27.399000 to 2018-05-23 11:18:27.950000
Labeling from 2018-05-23 11:18:33.758000 to 2018-05-23 11:18:34.309000
Labeling from 2018-05-23 11:18:34.256000 to 2018-05-23 11:18:34.807000
Labeling from 2018-05-23 11:18:37.447000 to 2018-05-23 11:18:37.998000
Labeling from 2018-05-23 11:18:38.004000 to 2018-05-23 11:18:38.555000
Labeling from 2018-05-23 11:18:40.768000 to 2018-05-23 11:18:41.319000

In [51]:
SE038_a1_ground_truth_df.head()

                   timestamp  ground_truth
0 2018-05-23 11:05:57.000000             0
1 2018-05-23 11:05:57.003906             0
2 2018-05-23 11:05:57.007812             0
3 2018-05-23 11:05:57.011718             0
4 2018-05-23 11:05:57.015625             0

In [52]:
print(SE038_a1_ground_truth_df.shape)
print(SE038_a1_df.shape)

(468480, 2)
(468480, 17)

In [53]:
SE038_a1_ground_truth_df.to_csv(
    RAW_KISPI_DATA_FOLDER / "SE038_a1_ground_truth.csv",
    date_format="%Y-%m-%d %H:%M:%S.%f")

### Merge Annotator-1 Dataframes

In [54]:
bipolar_SE008_a1 = SE008_a1_df.copy()    
bipolar_SE021_a1 = SE021_a1_df.copy()    
bipolar_SE026_a1 = SE026_a1_df.copy()    
bipolar_SE038_a1 = SE038_a1_df.copy()

In [55]:
bipolar_SE008_a1_merged = pd.merge(bipolar_SE008_a1, SE008_a1_ground_truth_df, left_index=True, right_on="timestamp") 
bipolar_SE021_a1_merged = pd.merge(bipolar_SE021_a1, SE021_a1_ground_truth_df, left_index=True, right_on="timestamp")
bipolar_SE026_a1_merged = pd.merge(bipolar_SE026_a1, SE026_a1_ground_truth_df, left_index=True, right_on="timestamp")
bipolar_SE038_a1_merged = pd.merge(bipolar_SE038_a1, SE038_a1_ground_truth_df, left_index=True, right_on="timestamp")

In [56]:
print(bipolar_SE008_a1_merged.shape)
print(bipolar_SE021_a1_merged.shape)
print(bipolar_SE026_a1_merged.shape)
print(bipolar_SE038_a1_merged.shape)

(9511168, 19)
(368640, 19)
(460800, 19)
(468480, 19)

#### Drop Datetime Index
We now drop the current datatime index.

This will allows us to create our `data_learning` (Train) and `data_testing` (Test) datasets.

In [57]:
bipolar_SE008_a1_merged.reset_index(drop=True, inplace=True)
print(bipolar_SE008_a1_merged.head(-1))

bipolar_SE021_a1_merged.reset_index(drop=True, inplace=True)

bipolar_SE026_a1_merged.reset_index(drop=True, inplace=True)

bipolar_SE038_a1_merged.reset_index(drop=True, inplace=True)

            Fp1-F7       F7-T3      T3-T5      Fp1-F3      F3-C3       C3-P3  \
0       -56.023338   60.677040 -19.330742  -29.175087  95.042793  -97.369652
1       -57.097267   63.182877 -18.435799  -28.817116  96.653694  -95.758751
2       -59.066147   64.256813 -15.214012  -29.712067  98.801559  -95.937744
3       -58.529175   64.972755 -15.929962  -29.891052  99.696503  -97.011673
4       -58.171211   65.151756 -18.614784  -28.996117  98.622574  -98.801559
...            ...         ...        ...         ...        ...         ...
9511162 -74.280151  113.120613 -60.856026  174.155640 -65.867706 -104.887161
9511163 -73.206238  107.929970 -61.750969  144.801544 -42.241245  -99.875488
9511164 -72.669266  103.813232 -59.961090  100.054474  -3.758757  -92.536957
9511165 -72.848236  105.603104 -57.813232  102.023354  -2.147861  -92.000000
9511166 -73.385223  111.330742 -58.887154  147.128403 -38.661480  -97.906616

             P3-O1       Fz-Cz      Cz-Pz     Fp2-F4      F4-C4      C4-P4  \
0        74.817123  -90.747086  11.276268 -45.105057  18.793770  74.459145
1        73.743187  -87.704285  11.276268 -42.957199  19.151749  74.459145
2        76.249031  -87.883270  10.739304 -42.778214  19.330742  75.891052
3        77.680931  -87.883270   9.307396 -42.599220  17.719841  75.712067
4        77.501953  -87.704285   8.770432 -42.957199  16.824905  74.817123
...            ...         ...        ...        ...        ...        ...
9511162  89.494171 -383.035034 -82.871597 -45.642025 -37.050583  57.276268
9511163  77.143974  -35.439686 -78.933853 -39.377430 -39.198441  56.202332
9511164  60.498055  384.645905 -72.848251 -35.797665 -40.988327  56.739296
9511165  62.645912  314.482483 -71.058365 -37.587551 -36.692604  60.319065
9511166  79.112839 -137.105057 -74.101166 -41.525291 -30.607010  63.719849

              P4-O2     Fp2-F8       F8-T4       T4-T6       T6-O2  \
0       -130.124512 -65.151756  148.918289   11.097277 -176.840454
1       -129.050583 -64.256813  149.097275   11.276265 -174.513611
2       -129.945526 -64.793770  150.350189   10.202334 -173.260696
3       -129.408569 -65.151749  149.634232   10.023346 -173.081726
4       -129.229568 -64.435799  147.307388   10.381323 -173.797668
...             ...        ...         ...         ...         ...
9511162 -174.871613   0.000000   64.077820 -138.715958 -125.649811
9511163 -177.377441   0.536964   61.214008 -135.494156 -126.007797
9511164 -177.735413   0.536964   53.696499 -125.828796 -126.186768
9511165 -177.735397   2.147861   54.591438 -123.143967 -125.291824
9511166 -179.525284   4.116734   63.719841 -129.766541 -126.007774

                         timestamp  ground_truth
0       2012-04-17 17:02:08.000000             0
1       2012-04-17 17:02:08.003906             0
2       2012-04-17 17:02:08.007812             0
3       2012-04-17 17:02:08.011718             0
4       2012-04-17 17:02:08.015625             0
...                            ...           ...
9511162 2012-04-18 03:21:20.976562             0
9511163 2012-04-18 03:21:20.980468             0
9511164 2012-04-18 03:21:20.984375             0
9511165 2012-04-18 03:21:20.988281             0
9511166 2012-04-18 03:21:20.992187             0

[9511167 rows x 19 columns]

#### Drop `Timestamp` column

In [58]:
bipolar_SE008_a1_merged.drop(columns="timestamp", inplace=True)
print(bipolar_SE008_a1_merged.head(-1))

bipolar_SE021_a1_merged.drop(columns="timestamp", inplace=True)
print(bipolar_SE021_a1_merged.head(-1))

bipolar_SE026_a1_merged.drop(columns="timestamp", inplace=True) 
print(bipolar_SE026_a1_merged.head(-1)) 

bipolar_SE038_a1_merged.drop(columns="timestamp", inplace=True)
print(bipolar_SE038_a1_merged.head(-1))

            Fp1-F7       F7-T3      T3-T5      Fp1-F3      F3-C3       C3-P3  \
0       -56.023338   60.677040 -19.330742  -29.175087  95.042793  -97.369652
1       -57.097267   63.182877 -18.435799  -28.817116  96.653694  -95.758751
2       -59.066147   64.256813 -15.214012  -29.712067  98.801559  -95.937744
3       -58.529175   64.972755 -15.929962  -29.891052  99.696503  -97.011673
4       -58.171211   65.151756 -18.614784  -28.996117  98.622574  -98.801559
...            ...         ...        ...         ...        ...         ...
9511162 -74.280151  113.120613 -60.856026  174.155640 -65.867706 -104.887161
9511163 -73.206238  107.929970 -61.750969  144.801544 -42.241245  -99.875488
9511164 -72.669266  103.813232 -59.961090  100.054474  -3.758757  -92.536957
9511165 -72.848236  105.603104 -57.813232  102.023354  -2.147861  -92.000000
9511166 -73.385223  111.330742 -58.887154  147.128403 -38.661480  -97.906616

             P3-O1       Fz-Cz      Cz-Pz     Fp2-F4      F4-C4      C4-P4  \
0        74.817123  -90.747086  11.276268 -45.105057  18.793770  74.459145
1        73.743187  -87.704285  11.276268 -42.957199  19.151749  74.459145
2        76.249031  -87.883270  10.739304 -42.778214  19.330742  75.891052
3        77.680931  -87.883270   9.307396 -42.599220  17.719841  75.712067
4        77.501953  -87.704285   8.770432 -42.957199  16.824905  74.817123
...            ...         ...        ...        ...        ...        ...
9511162  89.494171 -383.035034 -82.871597 -45.642025 -37.050583  57.276268
9511163  77.143974  -35.439686 -78.933853 -39.377430 -39.198441  56.202332
9511164  60.498055  384.645905 -72.848251 -35.797665 -40.988327  56.739296
9511165  62.645912  314.482483 -71.058365 -37.587551 -36.692604  60.319065
9511166  79.112839 -137.105057 -74.101166 -41.525291 -30.607010  63.719849

              P4-O2     Fp2-F8       F8-T4       T4-T6       T6-O2  \
0       -130.124512 -65.151756  148.918289   11.097277 -176.840454
1       -129.050583 -64.256813  149.097275   11.276265 -174.513611
2       -129.945526 -64.793770  150.350189   10.202334 -173.260696
3       -129.408569 -65.151749  149.634232   10.023346 -173.081726
4       -129.229568 -64.435799  147.307388   10.381323 -173.797668
...             ...        ...         ...         ...         ...
9511162 -174.871613   0.000000   64.077820 -138.715958 -125.649811
9511163 -177.377441   0.536964   61.214008 -135.494156 -126.007797
9511164 -177.735413   0.536964   53.696499 -125.828796 -126.186768
9511165 -177.735397   2.147861   54.591438 -123.143967 -125.291824
9511166 -179.525284   4.116734   63.719841 -129.766541 -126.007774

         ground_truth
0                   0
1                   0
2                   0
3                   0
4                   0
...               ...
9511162             0
9511163             0
9511164             0
9511165             0
9511166             0

[9511167 rows x 18 columns]
           Fp1-F7      F7-T3      T3-T5      Fp1-F3       F3-C3       C3-P3  \
0       34.186771  62.287937 -63.898834  141.758759 -108.645912  150.887161
1       35.260700  60.856033 -67.836578  140.863815 -109.361870  148.560303
2       34.902725  59.066147 -69.626465  139.789886 -110.077820  146.412445
3       35.260704  56.918289 -68.731522  138.536957 -109.540855  147.307404
4       36.155640  56.202335 -65.509727  139.431915 -108.287941  148.560303
...           ...        ...        ...         ...         ...         ...
368634  64.077820  40.451363 -72.132294  130.303497 -151.961090  175.229584
368635  63.361866  41.346306 -70.700394  130.482498 -149.634247  173.618683
368636  61.750973  42.062252 -69.626457  130.303497 -146.233459  172.007782
368637  60.319065  40.272377 -68.373543  130.482483 -147.307388  171.291824
368638  59.603111  38.482491 -66.225677  131.198441 -149.634232  172.365753

            P3-O1       Fz-Cz      Cz-Pz      Fp2-F4      F4-C4      C4-P4  \
0      -32.575874  141.937744 -18.972763  218.186768 -26.848248  28.459148
1      -31.322960  138.536957 -25.953306  219.618683 -27.385212  23.626461
2      -30.785988  138.000000 -28.459145  221.229568 -26.669258  20.941635
3      -32.396889  137.821014 -23.805447  224.809341 -25.416340  20.225681
4      -33.470818  138.536957 -16.108950  228.210114 -23.805450  19.688721
...           ...         ...        ...         ...        ...        ...
368634 -33.649811  124.396881  13.782101  196.171204 -25.774315  47.968872
368635 -32.754868  120.101166  16.466927  195.276260 -25.237350  46.178986
368636 -34.007782  122.070045   7.696498  195.634247 -26.311283  45.999996
368637 -35.618675  122.428017   1.789883  195.634247 -28.638134  45.463039
368638 -36.513618  124.754868   4.474709  195.813232 -28.101168  47.789879

            P4-O2     Fp2-F8      F8-T4       T4-T6       T6-O2  ground_truth
0      -39.735413  90.389099  97.190659  143.369644 -150.887146             0
1      -38.124519  90.210129  95.579765  142.832687 -150.887161             0
2      -39.556419  89.494164  96.653694  142.295715 -152.498047             0
3      -42.241245  92.357986  97.369652  141.221786 -153.571976             0
4      -43.852142  95.758759  96.832687  142.295715 -154.645920             0
...           ...        ...        ...         ...         ...           ...
368634  -6.801559  93.431908  93.789886  154.108948 -129.766541             0
368635  -5.190659  92.894943  95.579773  151.245148 -128.692612             0
368636  -5.369644  94.505829  94.684830  150.171204 -129.408554             0
368637  -6.622574  94.147865  94.326843  148.023346 -130.661484             0
368638 -11.813225  95.221794  92.536964  148.202332 -132.272369             0

[368639 rows x 18 columns]
           Fp1-F7      F7-T3       T3-T5      Fp1-F3       F3-C3       C3-P3  \
0      -28.638134 -57.276264 -122.785995  105.245132 -137.105057 -215.322952
1      -13.245135 -95.221794  -95.937744  110.972771 -116.521408 -226.062256
2      -14.319066 -93.968872 -105.424118  105.961082 -105.603104 -230.894943
3      -28.996109 -54.770428 -142.116730   98.980545 -110.435791 -228.568100
4      -38.482487 -30.785992 -159.120621   98.801559 -116.879379 -224.809341
...           ...        ...         ...         ...         ...         ...
460794 -70.879379 -49.042801   93.610901 -101.307388  -40.451363   69.984436
460795 -75.354080 -31.501945   76.070038 -104.708168  -39.377434   66.762650
460796 -73.385208 -22.373541   59.424126 -104.529182  -42.062256   64.077820
460797 -73.922180 -30.428013   63.719841 -107.392998  -47.073929   64.256805
460798 -76.249023 -40.630348   74.459145 -106.856033  -56.202335   67.478600

            P3-O1       Fz-Cz       Cz-Pz     Fp2-F4      F4-C4      C4-P4  \
0       43.315170 -142.474701 -141.937744  25.058365 -89.315170 -19.867706
1       38.840469 -124.217896 -131.914398  34.544746 -88.778214 -44.926071
2       28.996109 -117.058365 -143.369659  29.354088 -77.859924 -58.350189
3       13.424133 -127.618675 -170.933853  15.571983 -66.762650 -49.758759
4        3.579773 -136.389099 -186.147858  14.140076 -64.435791 -37.587555
...           ...         ...         ...        ...        ...        ...
460794  34.902725  -49.579769   75.354088  -6.443577 -54.054478  39.556423
460795  31.501945  -47.431908   65.688721 -11.634243 -52.980545  49.579765
460796  22.910505  -46.894943   51.011673 -19.151749 -49.400780  55.128407
460797  24.342413  -49.221790   54.949417 -17.540855 -54.412453  52.622570
460798  29.891052  -50.474709   71.774323 -14.498055 -59.603111  47.968872

             P4-O2     Fp2-F8      F8-T4      T4-T6      T6-O2  ground_truth
0       -27.743195 -74.101166  35.439682 -36.513611 -36.692612             0
1       -11.992218 -63.182884  35.797668 -40.988327 -42.778214             0
2       -21.478607 -65.509727  36.513626 -53.696503 -45.642029             0
3       -50.295715 -81.439690  36.513611 -57.992218 -48.326843             0
4       -67.299606 -90.747086  42.241257 -53.338531 -53.338516             0
...            ...        ...        ...        ...        ...           ...
460794 -103.276268 -81.618675  55.665371 -55.307396 -42.957199             0
460795 -110.972763 -84.482491  54.412453 -51.011673 -44.926071             0
460796 -118.311279 -85.556419  54.412453 -49.400780 -51.190659             0
460797 -113.836578 -84.840469  52.801559 -47.789886 -53.338516             0
460798 -107.750977 -85.019455  53.517509 -47.073929 -55.307392             0

[460799 rows x 18 columns]
            Fp1-F7      F7-T3       T3-T5      Fp1-F3       F3-C3       C3-P3  \
0       382.677063 -98.980545  164.490280  104.529190 -122.249039  479.330750
1       374.980530 -85.914398  163.953308  108.108948  -32.575874  389.657593
2       392.879395 -87.346306  158.941620   93.252914  -97.190659  480.941620
3       410.062256 -94.147865  158.225677   76.607010 -237.338516  645.252930
4       406.661499 -90.389099  161.089493   84.303513 -270.272400  672.638184
...            ...        ...         ...         ...         ...         ...
468474   97.548637 -98.801559   41.525291   33.649807   97.190666   18.256805
468475   64.972763 -81.618675   47.789883   31.143967   89.673149   13.961090
468476   24.163424 -56.739304   52.801559   26.311283   82.513618   12.887161
468477   30.428017 -57.276264   50.832684   28.817120   84.303505   15.392998
468478   74.817123 -81.618675   43.315174   35.081711   94.684822   16.466927

             P3-O1      Fz-Cz      Cz-Pz     Fp2-F4       F4-C4      C4-P4  \
0      -215.680923 -54.054470 -40.093388 -34.723724   69.805435 -95.400772
1      -218.723724 -56.918289 -44.210117 -25.953308   64.077820 -99.517502
2      -209.774307 -52.443581 -36.871597 -31.143967   84.482483 -96.653694
3      -199.213989 -48.326851 -26.848249 -43.494164  100.770424 -89.673149
4      -200.824921 -51.906616 -23.626461 -46.178986   91.284042 -85.019455
...            ...        ...        ...        ...         ...        ...
468474  -99.696495 -81.439690  60.140079  -5.011671   90.747078 -18.256805
468475  -90.210121 -87.704285  49.400776   0.178989   92.000000 -22.552528
468476  -80.902725 -94.863815  35.797668   4.295721   94.147858 -28.280151
468477  -85.556427 -92.715958  39.735409   3.221788   95.221794 -29.712067
468478  -99.696495 -83.229568  52.622566  -1.252918   95.400772 -27.564201

             P4-O2      Fp2-F8      F8-T4      T4-T6       T6-O2  ground_truth
0      -160.552521   42.420242 -75.533081 -99.875488  -87.883270             0
1      -167.175095   41.346313 -71.774323 -99.517517  -98.622566             0
2      -129.587555   48.326843 -73.385208 -98.443588  -49.400780             0
3       -94.863815   54.054474 -77.322960 -96.474709   -7.517509             0
4      -108.108940   53.338531 -76.785995 -95.937744  -28.638132             0
...            ...         ...        ...        ...         ...           ...
468474 -198.140076   86.630356   0.178986 -61.929958 -155.540863             0
468475 -222.840469   95.221786  -1.610886 -64.077820 -182.747086             0
468476 -250.225677  103.813225  -2.326843 -67.299606 -214.249023             0
468477 -244.677048  101.486382  -0.357986 -68.552521 -208.521408             0
468478 -211.743195   91.821014   3.400772 -68.194550 -172.186768             0

[468479 rows x 18 columns]

### Convert Annotator-2 Files

In [59]:
# convert all .edf files
for filename in tqdm(filenames_a2, desc='Converting EDF to Parquet'):
    # instantiate the AdvancedEdfToParquetConverter
    converter = AdvancedEdfToParquetConverter(
        edf_file_path=os.path.join(input_folder, filename),
        parquet_output_dir=output_folder,
        exclude_signals=["EEG A1", "EEG A2", "EKG", "EOG", "EMG", "PHO", "NASE"],
        group_by_sampling_freq=True,
        datetime_index=True,
        local_timezone=(pytz.timezone("Europe/Zurich"), pytz.timezone("Europe/Zurich")),
        compression_codec="GZIP"
    )
    
    # convert the EDF file to Parquet and save it to the output folder
    #converter.convert()

Converting EDF to Parquet: 100%|██████████| 2/2 [00:00<00:00, 12.22it/s]

#### TO DO: Convert remaining (Andreas) annotated files
- [X] ~~Convert SE038_annotated2.edf~~
- [ ] Convert SE008_annotated2.edf
- [ ] Convert SE026_annotated2.edf

#### Read Converted Parquet Annotator-2 File 
using handy pandas.

In [60]:
#SE008_a2_parquet_file_path = PROCESSED_KISPI_DATA_FOLDER / Path("SE008_a2.parquet") FILE CURRENTLY DOESN'T EXIST
SE021_a2_parquet_file_path = PROCESSED_KISPI_DATA_FOLDER / Path("SE021_a2.parquet")
#SE026_a2_parquet_file_path = PROCESSED_KISPI_DATA_FOLDER / Path("SE026_a2.parquet") FILE CURRENTLY DOESN'T EXIST
SE038_a2_parquet_file_path = PROCESSED_KISPI_DATA_FOLDER / Path("SE038_a2.parquet")

# convert WindowsPath to strings (to avoid encoding errors)
#SE008_a2_parquet_file_pat = str(SE008_a2_parquet_file_pat)
SE021_a2_parquet_file_path = str(SE021_a2_parquet_file_path)
#SE026_a2_parquet_file_pat = str(SE026_a2_parquet_file_path)
SE038_a2_parquet_file_path = str(SE038_a2_parquet_file_path)

#### Read Converted Parqeut Annotator-2 File 
using the `ParquetReader` directly

In [61]:
from edf2parquet.readers import ParquetReader

read_SE021_a2 = ParquetReader(parquet_file_path=SE021_a2_parquet_file_path)
SE021_a2_df = pd.read_parquet(SE021_a2_parquet_file_path, engine='pyarrow')

In [62]:
read_SE021_a2.get_file_header()

{'technician': '',
 'recording_additional': '',
 'patientname': 'X',
 'patient_additional': '',
 'patientcode': 'SE021 a2',
 'equipment': 'Deltamed',
 'admincode': 'SE021 150901U-C 0000',
 'sex': '',
 'startdate': Timestamp('2015-09-01 16:06:27+0200', tz='Europe/Zurich'),
 'birthdate': '',
 'gender': '',
 'tz_recording': 'Europe/Zurich',
 'tz_startdatetime': 'Europe/Zurich'}

In [63]:
#read_SE008_a2 = ParquetReader(parquet_file_path=SE008_a2_parquet_file_path)
#SE008_a2_df = read_SE008_a2.get_pandas_dataframe(set_timezone=True)

#read_SE026_a2 = ParquetReader(parquet_file_path=SE026_a2_parquet_file_path)
#SE026_a2_df = read_SE026_a2.get_pandas_dataframe(set_timezone=True)

read_SE038_a2 = ParquetReader(parquet_file_path=SE038_a2_parquet_file_path)
SE038_a2_df = pd.read_parquet(SE038_a2_parquet_file_path, engine='pyarrow')

In [64]:
#print(read_SE008_a2.get_file_header())
#print(read_SE026_a2.get_file_header())
print(read_SE038_a2.get_file_header())

{'technician': '', 'recording_additional': '', 'patientname': 'X', 'patient_additional': '', 'patientcode': 'SE038 a2', 'equipment': 'Deltamed', 'admincode': 'SE038 180523D-D', 'sex': '', 'startdate': Timestamp('2018-05-23 11:05:57+0200', tz='Europe/Zurich'), 'birthdate': '', 'gender': '', 'tz_recording': 'Europe/Zurich', 'tz_startdatetime': 'Europe/Zurich'}

#### Filter Data
Based on annotation lengths

##### Filter SE008_a2
by its unique `cutoff_time_SE008`

In [65]:
#print(SE008_a2_df.shape)

In [66]:
#SE008_a2_df = SE008_a2_df.copy()
#SE008_a2_df.index = SE008_a2_df.index.tz_localize(None)

In [67]:
#SE008_a2_df.head(-1)

`cutoff_time_SE008` previously defind

In [68]:

#SE008_a2_df = SE008_a2_df.loc[SE008_a2_df.index < cutoff_time_SE008]
#print(SE008_a1_df.head(-1))

`SE008_a2_df` went from [15010559 rows] to [9511167 rows]

##### Filter SE026_a2
by unique `cutoff_time_SE026`

In [69]:
#SE026_a2_df = SE026_a2_df.copy()
#SE026_a2_df.index = SE026_a2_df.index.tz_localize(None)

`cutoff_time_SE026` previously defined

In [70]:
#SE026_a2_df = SE026_a2_df.loc[SE026_a2_df.index < cutoff_time_SE026]
#print(SE026_a2_df.head(-1))

In [71]:
#SE026_a2_df.head(-1)

`SE026_a2_df` went from [1065215 rows] to [460799 rows]

##### Filter SE038_a2
by unique `cutoff_time_SE038`

In [72]:
SE038_a2_df = SE038_a2_df.copy()
SE038_a2_df.index = SE038_a2_df.index.tz_localize(None)

In [73]:
SE038_a2_df.head(-1)

,EEG Fp1,EEG Fp2,EEG F7,EEG F3,EEG Fz,EEG F4,EEG F8,EEG T3,EEG C3,EEG Cz,EEG C4,EEG T4,EEG T5,EEG P3,EEG Pz,EEG P4,EEG T6,EEG O1,EEG O2
2018-05-23 11:05:57.000000,153.840469,-192.322952,-228.836578,49.311283,-100.680931,-157.599228,-234.743195,-129.856033,171.560318,-46.626461,-227.404663,-159.210114,-294.346313,-307.770416,-6.533074,-132.003891,-59.334629,-92.089493,28.548637
2018-05-23 11:05:57.003906,154.019455,-189.280151,-220.961090,45.910507,-101.933853,-163.326843,-230.626465,-135.046692,78.486382,-45.015564,-227.404663,-158.852142,-299.000000,-311.171204,-0.805447,-127.887161,-59.334629,-92.447472,39.287937
2018-05-23 11:05:57.007812,185.163422,-161.715958,-207.715958,91.910507,-82.066147,-130.571991,-210.042801,-120.369652,189.101166,-29.622568,-215.054474,-136.657593,-279.311279,-291.840454,7.249027,-118.400780,-38.214008,-82.066147,11.186770
2018-05-23 11:05:57.011718,200.556427,-150.797668,-209.505844,123.949417,-70.789886,-107.303505,-204.852142,-115.357979,361.287933,-22.463036,-208.073929,-127.529182,-273.583649,-283.964966,4.385214,-118.400780,-31.054474,-84.750977,-23.536964
2018-05-23 11:05:57.015625,178.540863,-171.381317,-228.120621,94.237350,-85.287941,-125.202332,-224.719849,-137.731522,364.509735,-33.381325,-216.486374,-147.933853,-298.821014,-308.128418,-9.754864,-131.466919,-51.996109,-107.303505,-23.357977
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-05-23 12:50:31.976562,22.284046,-95.848251,-13.334630,-219.887161,-55.754864,33.202335,-37.856030,26.758755,-100.859924,-64.883270,-124.486382,-36.066147,-409.077820,-317.256805,-186.774323,-180.330734,-136.836578,-655.544739,-295.062256
2018-05-23 12:50:31.980468,22.105059,-89.941635,6.712062,-218.455246,-57.902725,34.634243,-46.805447,41.614784,-96.385216,-62.377434,-125.381325,-10.470818,-406.571991,-291.124512,-172.992218,-166.011673,-132.719849,-656.976624,-274.120636
2018-05-23 12:50:31.984375,21.210117,-79.560310,29.622568,-215.233459,-60.050583,36.424126,-47.521400,91.910507,-82.961090,-54.859921,-127.529182,-21.389105,-396.190674,-239.038910,-152.766541,-139.342407,-127.350197,-656.976624,-238.680939
2018-05-23 12:50:31.988281,23.536964,-87.614784,34.097275,-210.042801,-58.976654,39.645916,-44.657589,90.478600,-78.486382,-51.280155,-125.739296,-26.221790,-388.852142,-229.015564,-150.081711,-133.256805,-121.980545,-649.459167,-229.194550
2018-05-23 12:50:31.992187,33.918289,-93.521400,19.241245,-207.357971,-53.964981,40.540855,-36.245136,54.859921,-89.762650,-57.365757,-121.264595,-6.533074,-396.011688,-273.404663,-169.054474,-155.451355,-128.782104,-644.626465,-265.887146

`cutoff_time_SE038` previously defined

In [74]:
SE038_a2_df = SE038_a2_df.loc[SE038_a2_df.index < cutoff_time_SE038]
print(SE038_a2_df.head(-1))

                               EEG Fp1     EEG Fp2      EEG F7      EEG F3  \
2018-05-23 11:05:57.000000  153.840469 -192.322952 -228.836578   49.311283
2018-05-23 11:05:57.003906  154.019455 -189.280151 -220.961090   45.910507
2018-05-23 11:05:57.007812  185.163422 -161.715958 -207.715958   91.910507
2018-05-23 11:05:57.011718  200.556427 -150.797668 -209.505844  123.949417
2018-05-23 11:05:57.015625  178.540863 -171.381317 -228.120621   94.237350
...                                ...         ...         ...         ...
2018-05-23 11:36:26.976562   46.984436  -35.350193  -50.564201   13.334630
2018-05-23 11:36:26.980468   40.361866  -33.202335  -24.610895    9.217898
2018-05-23 11:36:26.984375   34.276264  -31.591440   10.112841    7.964981
2018-05-23 11:36:26.988281   38.750973  -30.338522    8.322957    9.933852
2018-05-23 11:36:26.992187   48.237354  -29.443581  -26.579767   13.155642

                                EEG Fz      EEG F4      EEG F8      EEG T3  \
2018-05-23 11:05:57.000000 -100.680931 -157.599228 -234.743195 -129.856033
2018-05-23 11:05:57.003906 -101.933853 -163.326843 -230.626465 -135.046692
2018-05-23 11:05:57.007812  -82.066147 -130.571991 -210.042801 -120.369652
2018-05-23 11:05:57.011718  -70.789886 -107.303505 -204.852142 -115.357979
2018-05-23 11:05:57.015625  -85.287941 -125.202332 -224.719849 -137.731522
...                                ...         ...         ...         ...
2018-05-23 11:36:26.976562  -27.474709  -30.338522 -121.980545   48.237354
2018-05-23 11:36:26.980468  -33.381325  -33.381325 -128.424118   57.007782
2018-05-23 11:36:26.984375  -38.929962  -35.887161 -135.404663   66.852142
2018-05-23 11:36:26.988281  -35.529182  -33.560310 -131.824905   65.599220
2018-05-23 11:36:26.992187  -28.190662  -28.190662 -121.264595   55.038910

                                EEG C3     EEG Cz      EEG C4      EEG T4  \
2018-05-23 11:05:57.000000  171.560318 -46.626461 -227.404663 -159.210114
2018-05-23 11:05:57.003906   78.486382 -45.015564 -227.404663 -158.852142
2018-05-23 11:05:57.007812  189.101166 -29.622568 -215.054474 -136.657593
2018-05-23 11:05:57.011718  361.287933 -22.463036 -208.073929 -127.529182
2018-05-23 11:05:57.015625  364.509735 -33.381325 -216.486374 -147.933853
...                                ...        ...         ...         ...
2018-05-23 11:36:26.976562  -83.856033  53.964981 -121.085602 -122.159531
2018-05-23 11:36:26.980468  -80.455254  54.322956 -125.381325 -126.813232
2018-05-23 11:36:26.984375  -74.548637  55.933853 -130.035019 -133.077820
2018-05-23 11:36:26.988281  -74.369652  57.186771 -128.782104 -131.466919
2018-05-23 11:36:26.992187  -81.529182  55.038910 -123.591438 -124.665367

                                EEG T5      EEG P3     EEG Pz      EEG P4  \
2018-05-23 11:05:57.000000 -294.346313 -307.770416  -6.533074 -132.003891
2018-05-23 11:05:57.003906 -299.000000 -311.171204  -0.805447 -127.887161
2018-05-23 11:05:57.007812 -279.311279 -291.840454   7.249027 -118.400780
2018-05-23 11:05:57.011718 -273.583649 -283.964966   4.385214 -118.400780
2018-05-23 11:05:57.015625 -298.821014 -308.128418  -9.754864 -131.466919
...                                ...         ...        ...         ...
2018-05-23 11:36:26.976562    6.712062 -102.112839  -6.175097 -102.828796
2018-05-23 11:36:26.980468    9.217898  -94.416344   4.922179 -102.828796
2018-05-23 11:36:26.984375   14.050584  -87.435799  20.136187 -101.754868
2018-05-23 11:36:26.988281   14.766537  -89.762650  17.451363  -99.070038
2018-05-23 11:36:26.992187   11.723736  -97.996109   2.416342  -96.027237

                               EEG T6      EEG O1      EEG O2
2018-05-23 11:05:57.000000 -59.334629  -92.089493   28.548637
2018-05-23 11:05:57.003906 -59.334629  -92.447472   39.287937
2018-05-23 11:05:57.007812 -38.214008  -82.066147   11.186770
2018-05-23 11:05:57.011718 -31.054474  -84.750977  -23.536964
2018-05-23 11:05:57.015625 -51.996109 -107.303505  -23.357977
...                               ...         ...         ...
2018-05-23 11:36:26.976562 -60.229572   -2.416342   95.311287
2018-05-23 11:36:26.980468 -62.735409   -4.206226  120.011673
2018-05-23 11:36:26.984375 -65.778214   -6.533074  148.470810
2018-05-23 11:36:26.988281 -62.914398   -4.206226  145.607010
2018-05-23 11:36:26.992187 -56.470818    1.700389  115.715950

[468479 rows x 19 columns]

`SE038_a2_df` went from [1606399 rows] to [468479 rows]

#### Create Bipolar Channel Pairs

In [75]:
#SE008_a2_df = create_bipolar_channels(SE008_a2_df)
SE021_a2_df = create_bipolar_channels(SE021_a2_df)
#SE026_a2_df = create_bipolar_channels(SE026_a2_df)
SE038_a2_df = create_bipolar_channels(SE038_a2_df)

In [76]:
#print(f"SE008_a2_df",SE008_a2_df.head())
print(f"SE021_a2_df",SE021_a2_df.head())
#print(f"SE026_a2_df",SE026_a2_df.head())
print(f"SE038_a2_df",SE038_a2_df.head())

SE021_a2_df                                Fp1-F7      F7-T3      T3-T5      Fp1-F3  \
2015-09-01 16:06:27.000000  34.186771  62.287937 -63.898834  141.758759
2015-09-01 16:06:27.003906  35.260700  60.856033 -67.836578  140.863815
2015-09-01 16:06:27.007812  34.902725  59.066147 -69.626465  139.789886
2015-09-01 16:06:27.011718  35.260704  56.918289 -68.731522  138.536957
2015-09-01 16:06:27.015625  36.155640  56.202335 -65.509727  139.431915

                                 F3-C3       C3-P3      P3-O1       Fz-Cz  \
2015-09-01 16:06:27.000000 -108.645912  150.887161 -32.575874  141.937744
2015-09-01 16:06:27.003906 -109.361870  148.560303 -31.322960  138.536957
2015-09-01 16:06:27.007812 -110.077820  146.412445 -30.785988  138.000000
2015-09-01 16:06:27.011718 -109.540855  147.307404 -32.396889  137.821014
2015-09-01 16:06:27.015625 -108.287941  148.560303 -33.470818  138.536957

                                Cz-Pz      Fp2-F4      F4-C4      C4-P4  \
2015-09-01 16:06:27.000000 -18.972763  218.186768 -26.848248  28.459148
2015-09-01 16:06:27.003906 -25.953306  219.618683 -27.385212  23.626461
2015-09-01 16:06:27.007812 -28.459145  221.229568 -26.669258  20.941635
2015-09-01 16:06:27.011718 -23.805447  224.809341 -25.416340  20.225681
2015-09-01 16:06:27.015625 -16.108950  228.210114 -23.805450  19.688721

                                P4-O2     Fp2-F8      F8-T4       T4-T6  \
2015-09-01 16:06:27.000000 -39.735413  90.389099  97.190659  143.369644
2015-09-01 16:06:27.003906 -38.124519  90.210129  95.579765  142.832687
2015-09-01 16:06:27.007812 -39.556419  89.494164  96.653694  142.295715
2015-09-01 16:06:27.011718 -42.241245  92.357986  97.369652  141.221786
2015-09-01 16:06:27.015625 -43.852142  95.758759  96.832687  142.295715

                                 T6-O2
2015-09-01 16:06:27.000000 -150.887146
2015-09-01 16:06:27.003906 -150.887161
2015-09-01 16:06:27.007812 -152.498047
2015-09-01 16:06:27.011718 -153.571976
2015-09-01 16:06:27.015625 -154.645920
SE038_a2_df                                 Fp1-F7      F7-T3       T3-T5      Fp1-F3  \
2018-05-23 11:05:57.000000  382.677063 -98.980545  164.490280  104.529190
2018-05-23 11:05:57.003906  374.980530 -85.914398  163.953308  108.108948
2018-05-23 11:05:57.007812  392.879395 -87.346306  158.941620   93.252914
2018-05-23 11:05:57.011718  410.062256 -94.147865  158.225677   76.607010
2018-05-23 11:05:57.015625  406.661499 -90.389099  161.089493   84.303513

                                 F3-C3       C3-P3       P3-O1      Fz-Cz  \
2018-05-23 11:05:57.000000 -122.249039  479.330750 -215.680923 -54.054470
2018-05-23 11:05:57.003906  -32.575874  389.657593 -218.723724 -56.918289
2018-05-23 11:05:57.007812  -97.190659  480.941620 -209.774307 -52.443581
2018-05-23 11:05:57.011718 -237.338516  645.252930 -199.213989 -48.326851
2018-05-23 11:05:57.015625 -270.272400  672.638184 -200.824921 -51.906616

                                Cz-Pz     Fp2-F4       F4-C4      C4-P4  \
2018-05-23 11:05:57.000000 -40.093388 -34.723724   69.805435 -95.400772
2018-05-23 11:05:57.003906 -44.210117 -25.953308   64.077820 -99.517502
2018-05-23 11:05:57.007812 -36.871597 -31.143967   84.482483 -96.653694
2018-05-23 11:05:57.011718 -26.848249 -43.494164  100.770424 -89.673149
2018-05-23 11:05:57.015625 -23.626461 -46.178986   91.284042 -85.019455

                                 P4-O2     Fp2-F8      F8-T4      T4-T6  \
2018-05-23 11:05:57.000000 -160.552521  42.420242 -75.533081 -99.875488
2018-05-23 11:05:57.003906 -167.175095  41.346313 -71.774323 -99.517517
2018-05-23 11:05:57.007812 -129.587555  48.326843 -73.385208 -98.443588
2018-05-23 11:05:57.011718  -94.863815  54.054474 -77.322960 -96.474709
2018-05-23 11:05:57.015625 -108.108940  53.338531 -76.785995 -95.937744

                                T6-O2
2018-05-23 11:05:57.000000 -87.883270
2018-05-23 11:05:57.003906 -98.622566
2018-05-23 11:05:57.007812 -49.400780
2018-05-23 11:05:57.011718  -7.517509
2018-05-23 11:05:57.015625 -28.638132

#### Create Ground Truth Labels
Using `_annotations.txt` files for all patients

#### TO DO: Missing Ground Truth Labels
for remaining (Andreas) annotated files
- [X] ~~Convert SE038_annotated2.edf~~
- [ ] Convert SE008_annotated2_annotations.txt
- [ ] Convert SE026_annotated2_annotations.txt

In [77]:
# SE008_a2_annotations = pd.read_csv(RAW_KISPI_DATA_FOLDER / "SE008_annotated2_annotations.txt")
SE021_a2_annotations = pd.read_csv(RAW_KISPI_DATA_FOLDER / "SE021_annotated2_annotations.txt")
#SE026_a2_annotations = pd.read_csv(RAW_KISPI_DATA_FOLDER / "SE026_annotated2_annotations.txt") # FILE CURRENTLY DOESN'T EXIST  
SE038_a2_annotations = pd.read_csv(RAW_KISPI_DATA_FOLDER / "SE038_annotated2_annotations.txt")

##### SE008_a2 Ground Truth Labels
Create `SE008_a2_ground_truth_df`

In [78]:
# SE008_a2_annotations["Onset"] = pd.to_datetime(SE008_a2_annotations["Onset"], format="%Y-%m-%dT%H:%M:%S.%f")
# 
# SE008_a2_timestamps = SE008_a2_df.index
# SE008_a2_ground_truth_df = pd.DataFrame(
#     {"timestamp" : SE008_a1_timestamps, "ground_truth" : 0}
#     )
# 
# SE008_a2_ground_truth_df["timestamp"] = pd.to_datetime(SE008_a2_ground_truth_df["timestamp"], format="%Y-%m-%dT%H:%M:%S.%f")
# 
# for index, row in SE008_a2_annotations.iterrows():
#     if row["Annotation"] == "Burst starts":
#         start_time = row["Onset"]
#         try:
#             # find the next row where the annotation is "Burst end"
#             end_time = SE008_a2_annotations.loc[
#                 (SE008_a1_annotations["Annotation"] == "Burst end") &
#                 (SE008_a1_annotations.index > index), "Onset"
#             ].iloc[0]
#         
#             SE008_a2_ground_truth_df.loc[
#                 (SE008_a2_ground_truth_df["timestamp"] >= start_time) 
#                 & (SE008_a2_ground_truth_df["timestamp"] <= end_time), 
#                 "ground_truth",] = 1
#         except IndexError:
#             print(f"Warning: No matching 'Burst end' annotation found for 'Burst starts' at {start_time}")

In [79]:
# SE008_a1_ground_truth_df.head()

In [80]:
# print(SE008_a2_ground_truth_df.shape)
# print(SE008_a2_df.shape)

##### SE021_a2 Ground Truth Labels
Create `SE021_a2_ground_truth_df`

In [81]:
SE021_a2_annotations.head()

                         Onset  Duration Annotation
0  2015-09-01T16:09:25.5570000     0.499      Burst
1  2015-09-01T16:09:45.2990000     0.525      Burst
2  2015-09-01T16:09:48.3110000     0.511      Burst
3  2015-09-01T16:09:52.3260000     0.550      Burst
4  2015-09-01T16:10:42.1490000     0.466      Burst

In [82]:
SE021_a2_df.index = SE021_a2_df.index.tz_localize(None)

In [83]:
SE021_a2_annotations["Onset"] = pd.to_datetime(SE021_a2_annotations["Onset"], format="%Y-%m-%dT%H:%M:%S.%f")

SE021_a2_timestamps = SE021_a2_df.index

SE021_a2_ground_truth_df = pd.DataFrame(
    {"timestamp" : SE021_a2_timestamps, "ground_truth" : 0}
    )

SE021_a2_ground_truth_df["timestamp"] = pd.to_datetime(SE021_a2_ground_truth_df["timestamp"], format="%Y-%m-%dT%H:%M:%S.%f")

# label "burst" or "Burst Suppression" annotations with duration
for index, row in SE021_a2_annotations.iterrows():
    if row["Annotation"] == "burst" or "Burst Suppression" and pd.notna(row["Duration"]):
        start_time = row["Onset"]
        end_time = start_time + pd.to_timedelta(row["Duration"], unit='s')  # calculate end_time using duration
        
        print(f"Labeling from {start_time} to {end_time}")

        SE021_a2_ground_truth_df.loc[
            (SE021_a2_ground_truth_df["timestamp"] >= start_time)
            & (SE021_a2_ground_truth_df["timestamp"] <= end_time),
            "ground_truth",
        ] = 1

Labeling from 2015-09-01 16:09:25.557000 to 2015-09-01 16:09:26.056000
Labeling from 2015-09-01 16:09:45.299000 to 2015-09-01 16:09:45.824000
Labeling from 2015-09-01 16:09:48.311000 to 2015-09-01 16:09:48.822000
Labeling from 2015-09-01 16:09:52.326000 to 2015-09-01 16:09:52.876000
Labeling from 2015-09-01 16:10:42.149000 to 2015-09-01 16:10:42.615000
Labeling from 2015-09-01 16:11:05.880000 to 2015-09-01 16:11:06.385000
Labeling from 2015-09-01 16:12:06.905000 to 2015-09-01 16:12:07.357000
Labeling from 2015-09-01 16:12:29.682000 to 2015-09-01 16:12:30.226000
Labeling from 2015-09-01 16:12:34.741000 to 2015-09-01 16:12:35.226000
Labeling from 2015-09-01 16:13:23.933000 to 2015-09-01 16:13:24.457000
Labeling from 2015-09-01 16:13:34.051000 to 2015-09-01 16:13:34.654000
Labeling from 2015-09-01 16:14:14.651000 to 2015-09-01 16:14:15.176000
Labeling from 2015-09-01 16:14:23.448000 to 2015-09-01 16:14:23.835000
Labeling from 2015-09-01 16:14:34.990000 to 2015-09-01 16:14:35.468000
Labeling from 2015-09-01 16:14:46.628000 to 2015-09-01 16:14:47.263000
Labeling from 2015-09-01 16:14:51.900000 to 2015-09-01 16:14:52.392000
Labeling from 2015-09-01 16:14:54.730000 to 2015-09-01 16:14:55.064000
Labeling from 2015-09-01 16:15:16.208000 to 2015-09-01 16:15:16.719000
Labeling from 2015-09-01 16:15:19.514000 to 2015-09-01 16:15:19.861000
Labeling from 2015-09-01 16:15:33.319000 to 2015-09-01 16:15:33.706000
Labeling from 2015-09-01 16:15:47.581000 to 2015-09-01 16:15:47.961000
Labeling from 2015-09-01 16:15:50.352000 to 2015-09-01 16:15:50.778000
Labeling from 2015-09-01 16:15:53.118000 to 2015-09-01 16:15:53.511000
Labeling from 2015-09-01 16:16:35.836000 to 2015-09-01 16:16:36.236000
Labeling from 2015-09-01 16:16:38.260000 to 2015-09-01 16:16:38.739000
Labeling from 2015-09-01 16:17:06.645000 to 2015-09-01 16:17:07.038000
Labeling from 2015-09-01 16:17:09.900000 to 2015-09-01 16:17:10.261000
Labeling from 2015-09-01 16:20:33.699000 to 2015-09-01 16:20:34.112000
Labeling from 2015-09-01 16:21:07.690000 to 2015-09-01 16:21:08.228000
Labeling from 2015-09-01 16:21:42.802000 to 2015-09-01 16:21:43.280000
Labeling from 2015-09-01 16:22:45.201000 to 2015-09-01 16:22:45.798000
Labeling from 2015-09-01 16:23:25.162000 to 2015-09-01 16:23:25.660000
Labeling from 2015-09-01 16:23:28.166000 to 2015-09-01 16:23:28.887000
Labeling from 2015-09-01 16:25:19.385000 to 2015-09-01 16:25:20.066000
Labeling from 2015-09-01 16:25:22.614000 to 2015-09-01 16:25:23.053000
Labeling from 2015-09-01 16:26:07.286000 to 2015-09-01 16:26:07.870000
Labeling from 2015-09-01 16:26:15.712000 to 2015-09-01 16:26:16.138000
Labeling from 2015-09-01 16:27:14.535000 to 2015-09-01 16:27:14.988000
Labeling from 2015-09-01 16:27:29.986000 to 2015-09-01 16:27:30.399000
Labeling from 2015-09-01 16:28:55.123000 to 2015-09-01 16:28:55.575000
Labeling from 2015-09-01 16:28:58.284000 to 2015-09-01 16:28:58.743000
Labeling from 2015-09-01 16:29:09.260000 to 2015-09-01 16:29:09.739000

In [84]:
SE021_a2_ground_truth_df.head(-1)

                        timestamp  ground_truth
0      2015-09-01 16:06:27.000000             0
1      2015-09-01 16:06:27.003906             0
2      2015-09-01 16:06:27.007812             0
3      2015-09-01 16:06:27.011718             0
4      2015-09-01 16:06:27.015625             0
...                           ...           ...
368634 2015-09-01 16:30:26.976562             0
368635 2015-09-01 16:30:26.980468             0
368636 2015-09-01 16:30:26.984375             0
368637 2015-09-01 16:30:26.988281             0
368638 2015-09-01 16:30:26.992187             0

[368639 rows x 2 columns]

In [85]:
print(SE021_a2_ground_truth_df.shape)
print(SE021_a2_df.shape)

(368640, 2)
(368640, 17)

In [86]:
SE021_a2_ground_truth_df.to_csv(
    RAW_KISPI_DATA_FOLDER / "SE021_a2_ground_truth.csv",
    date_format="%Y-%m-%d %H:%M:%S.%f")

##### SE026_a2 Ground Truth Labels
Create `SE026_a2_ground_truth_df`

In [87]:
# SE026_a2_annotations.head(-1)

In [88]:
# SE026_a2_df.index = SE026_a2_df.index.tz_localize(None)

In [89]:
# SE026_a2_annotations["Onset"] = pd.to_datetime(SE026_a2_annotations["Onset"], format="%Y-%m-%dT%H:%M:%S.%f")
# 
# SE026_a2_timestamps = SE026_a2_df.index
# 
# SE026_a2_ground_truth_df = pd.DataFrame(
#     {"timestamp" : SE026_a2_timestamps, "ground_truth" : 0}
#     )
# 
# SE026_a2_ground_truth_df["timestamp"] = pd.to_datetime(SE026_a2_ground_truth_df["timestamp"], format="%Y-%m-%dT%H:%M:%S.%f")
# 
# burst_count = 0
# for index, row in SE026_a2_annotations.iterrows():
#     if row["Annotation"] == "burst":
#         burst_count += 1
#         if burst_count % 2 == 0:  # Check if it's an even count (should be a closing 'burst')
#             end_time = row["Onset"]
#             
#             SE026_a2_ground_truth_df.loc[
#                 (SE026_a2_ground_truth_df["timestamp"] >= start_time)
#                 & (SE026_a2_ground_truth_df["timestamp"] <= end_time),
#                 "ground_truth",
#             ] = 1
#         else:
#             start_time = row["Onset"]
# 
# if burst_count % 2 != 0:
#     print(f"Warning: Unclosed 'burst' at {start_time}")

In [90]:
# SE026_a2_ground_truth_df.head()

In [91]:
# print(SE026_a2_ground_truth_df.shape)
# print(SE026_a2_df.shape)

##### SE038_a2 Ground Truth Labels
Create `SE038_a2_ground_truth_df`

In [92]:
SE038_a2_annotations.head(-1)

                           Onset  Duration         Annotation
0    2018-05-23T11:06:00.5960000     0.460  Burst Suppression
1    2018-05-23T11:06:05.2390000     0.459  Burst Suppression
2    2018-05-23T11:06:21.2620000     0.387  Burst Suppression
3    2018-05-23T11:06:27.7700000     0.584  Burst Suppression
4    2018-05-23T11:06:31.1030000     0.452              Burst
..                           ...       ...                ...
224  2018-05-23T11:34:40.5140000     0.335              Burst
225  2018-05-23T11:34:48.1240000     0.460              Burst
226  2018-05-23T11:34:54.0000000     0.282              Burst
227  2018-05-23T11:34:59.3960000     0.335              Burst
228  2018-05-23T11:35:08.4290000     0.322              Burst

[229 rows x 3 columns]

In [93]:
SE038_a2_annotations["Onset"] = pd.to_datetime(SE038_a2_annotations["Onset"], format="%Y-%m-%dT%H:%M:%S.%f")

SE038_a2_timestamps = SE038_a2_df.index

SE038_a2_ground_truth_df = pd.DataFrame(
    {"timestamp" : SE038_a2_timestamps, "ground_truth" : 0}
    )

SE038_a2_ground_truth_df["timestamp"] = pd.to_datetime(SE038_a2_ground_truth_df["timestamp"], format="%Y-%m-%dT%H:%M:%S.%f")

# label "burst" or "Burst Suppression" annotations with duration
for index, row in SE038_a2_annotations.iterrows():
    if row["Annotation"] == "burst" or "Burst Suppression" and pd.notna(row["Duration"]):
        start_time = row["Onset"]
        end_time = start_time + pd.to_timedelta(row["Duration"], unit='s')  # calculate end_time using duration
        
        print(f"Labeling from {start_time} to {end_time}")

        SE038_a2_ground_truth_df.loc[
            (SE038_a2_ground_truth_df["timestamp"] >= start_time)
            & (SE038_a2_ground_truth_df["timestamp"] <= end_time),
            "ground_truth",
        ] = 1

Labeling from 2018-05-23 11:06:00.596000 to 2018-05-23 11:06:01.056000
Labeling from 2018-05-23 11:06:05.239000 to 2018-05-23 11:06:05.698000
Labeling from 2018-05-23 11:06:21.262000 to 2018-05-23 11:06:21.649000
Labeling from 2018-05-23 11:06:27.770000 to 2018-05-23 11:06:28.354000
Labeling from 2018-05-23 11:06:31.103000 to 2018-05-23 11:06:31.555000
Labeling from 2018-05-23 11:06:38.170000 to 2018-05-23 11:06:38.577000
Labeling from 2018-05-23 11:06:42.795000 to 2018-05-23 11:06:43.109000
Labeling from 2018-05-23 11:06:49.039000 to 2018-05-23 11:06:49.374000
Labeling from 2018-05-23 11:06:53.330000 to 2018-05-23 11:06:53.664000
Labeling from 2018-05-23 11:06:58.546000 to 2018-05-23 11:06:58.821000
Labeling from 2018-05-23 11:07:02.878000 to 2018-05-23 11:07:03.258000
Labeling from 2018-05-23 11:07:06.880000 to 2018-05-23 11:07:07.227000
Labeling from 2018-05-23 11:07:10.533000 to 2018-05-23 11:07:10.841000
Labeling from 2018-05-23 11:07:15.738000 to 2018-05-23 11:07:16.151000
Labeling from 2018-05-23 11:07:21.747000 to 2018-05-23 11:07:22.271000
Labeling from 2018-05-23 11:07:27.670000 to 2018-05-23 11:07:28.050000
Labeling from 2018-05-23 11:07:32.662000 to 2018-05-23 11:07:32.944000
Labeling from 2018-05-23 11:07:36.736000 to 2018-05-23 11:07:37.083000
Labeling from 2018-05-23 11:07:43.238000 to 2018-05-23 11:07:43.605000
Labeling from 2018-05-23 11:07:47.860000 to 2018-05-23 11:07:48.168000
Labeling from 2018-05-23 11:07:51.550000 to 2018-05-23 11:07:51.950000
Labeling from 2018-05-23 11:07:54.917000 to 2018-05-23 11:07:55.245000
Labeling from 2018-05-23 11:07:59.316000 to 2018-05-23 11:07:59.599000
Labeling from 2018-05-23 11:08:06.969000 to 2018-05-23 11:08:07.396000
Labeling from 2018-05-23 11:08:09.559000 to 2018-05-23 11:08:09.880000
Labeling from 2018-05-23 11:08:13.391000 to 2018-05-23 11:08:13.811000
Labeling from 2018-05-23 11:08:19.021000 to 2018-05-23 11:08:19.323000
Labeling from 2018-05-23 11:08:24.208000 to 2018-05-23 11:08:24.516000
Labeling from 2018-05-23 11:08:30.867000 to 2018-05-23 11:08:31.123000
Labeling from 2018-05-23 11:08:36.004000 to 2018-05-23 11:08:36.346000
Labeling from 2018-05-23 11:08:41.667000 to 2018-05-23 11:08:42.021000
Labeling from 2018-05-23 11:08:46.313000 to 2018-05-23 11:08:46.634000
Labeling from 2018-05-23 11:08:50.339000 to 2018-05-23 11:08:50.720000
Labeling from 2018-05-23 11:08:54.968000 to 2018-05-23 11:08:55.336000
Labeling from 2018-05-23 11:09:00.791000 to 2018-05-23 11:09:01.139000
Labeling from 2018-05-23 11:09:05.480000 to 2018-05-23 11:09:05.782000
Labeling from 2018-05-23 11:09:10.532000 to 2018-05-23 11:09:10.920000
Labeling from 2018-05-23 11:09:13.018000 to 2018-05-23 11:09:13.425000
Labeling from 2018-05-23 11:09:16.050000 to 2018-05-23 11:09:16.425000
Labeling from 2018-05-23 11:09:22.618000 to 2018-05-23 11:09:22.900000
Labeling from 2018-05-23 11:09:28.267000 to 2018-05-23 11:09:28.608000
Labeling from 2018-05-23 11:09:32.326000 to 2018-05-23 11:09:32.720000
Labeling from 2018-05-23 11:09:36.988000 to 2018-05-23 11:09:37.284000
Labeling from 2018-05-23 11:09:36.988000 to 2018-05-23 11:09:43.316000
Labeling from 2018-05-23 11:09:46.801000 to 2018-05-23 11:09:47.129000
Labeling from 2018-05-23 11:09:53.083000 to 2018-05-23 11:09:53.366000
Labeling from 2018-05-23 11:09:59.018000 to 2018-05-23 11:09:59.320000
Labeling from 2018-05-23 11:10:05.431000 to 2018-05-23 11:10:05.687000
Labeling from 2018-05-23 11:10:09.719000 to 2018-05-23 11:10:09.989000
Labeling from 2018-05-23 11:10:13.273000 to 2018-05-23 11:10:13.641000
Labeling from 2018-05-23 11:10:17.280000 to 2018-05-23 11:10:17.543000
Labeling from 2018-05-23 11:10:20.985000 to 2018-05-23 11:10:21.293000
Labeling from 2018-05-23 11:10:23.899000 to 2018-05-23 11:10:24.143000
Labeling from 2018-05-23 11:10:29.214000 to 2018-05-23 11:10:29.477000
Labeling from 2018-05-23 11:10:32.486000 to 2018-05-23 11:10:32.756000
Labeling from 2018-05-23 11:10:36.132000 to 2018-05-23 11:10:36.408000
Labeling from 2018-05-23 11:10:41.663000 to 2018-05-23 11:10:41.966000
Labeling from 2018-05-23 11:10:46.247000 to 2018-05-23 11:10:46.484000
Labeling from 2018-05-23 11:10:50.499000 to 2018-05-23 11:10:50.756000
Labeling from 2018-05-23 11:10:55.011000 to 2018-05-23 11:10:55.280000
Labeling from 2018-05-23 11:10:59.490000 to 2018-05-23 11:10:59.733000
Labeling from 2018-05-23 11:11:03.640000 to 2018-05-23 11:11:04.008000
Labeling from 2018-05-23 11:11:09.677000 to 2018-05-23 11:11:09.952000
Labeling from 2018-05-23 11:11:09.677000 to 2018-05-23 11:11:09.952000
Labeling from 2018-05-23 11:11:09.677000 to 2018-05-23 11:11:15.018000
Labeling from 2018-05-23 11:11:14.736000 to 2018-05-23 11:11:14.998000
Labeling from 2018-05-23 11:11:28.503000 to 2018-05-23 11:11:28.759000
Labeling from 2018-05-23 11:11:32.952000 to 2018-05-23 11:11:33.234000
Labeling from 2018-05-23 11:11:38.145000 to 2018-05-23 11:11:38.480000
Labeling from 2018-05-23 11:11:43.083000 to 2018-05-23 11:11:43.385000
Labeling from 2018-05-23 11:11:47.995000 to 2018-05-23 11:11:48.284000
Labeling from 2018-05-23 11:11:52.916000 to 2018-05-23 11:11:53.185000
Labeling from 2018-05-23 11:11:56.863000 to 2018-05-23 11:11:57.107000
Labeling from 2018-05-23 11:12:01.024000 to 2018-05-23 11:12:01.366000
Labeling from 2018-05-23 11:12:12.561000 to 2018-05-23 11:12:12.870000
Labeling from 2018-05-23 11:12:16.178000 to 2018-05-23 11:12:16.512000
Labeling from 2018-05-23 11:12:24.604000 to 2018-05-23 11:12:24.919000
Labeling from 2018-05-23 11:12:28.053000 to 2018-05-23 11:12:28.342000
Labeling from 2018-05-23 11:12:31.322000 to 2018-05-23 11:12:31.637000
Labeling from 2018-05-23 11:12:36.732000 to 2018-05-23 11:12:36.981000
Labeling from 2018-05-23 11:12:41.076000 to 2018-05-23 11:12:41.371000
Labeling from 2018-05-23 11:12:45.909000 to 2018-05-23 11:12:46.217000
Labeling from 2018-05-23 11:12:49.319000 to 2018-05-23 11:12:49.667000
Labeling from 2018-05-23 11:12:53.810000 to 2018-05-23 11:12:54.099000
Labeling from 2018-05-23 11:12:59.299000 to 2018-05-23 11:12:59.588000
Labeling from 2018-05-23 11:13:04.364000 to 2018-05-23 11:13:04.634000
Labeling from 2018-05-23 11:13:07.935000 to 2018-05-23 11:13:08.224000
Labeling from 2018-05-23 11:13:13.404000 to 2018-05-23 11:13:13.680000
Labeling from 2018-05-23 11:13:18.860000 to 2018-05-23 11:13:19.155000
Labeling from 2018-05-23 11:13:23.194000 to 2018-05-23 11:13:23.431000
Labeling from 2018-05-23 11:13:27.364000 to 2018-05-23 11:13:27.667000
Labeling from 2018-05-23 11:13:34.417000 to 2018-05-23 11:13:34.745000
Labeling from 2018-05-23 11:13:38.863000 to 2018-05-23 11:13:39.053000
Labeling from 2018-05-23 11:13:43.230000 to 2018-05-23 11:13:43.526000
Labeling from 2018-05-23 11:13:47.843000 to 2018-05-23 11:13:48.139000
Labeling from 2018-05-23 11:13:52.381000 to 2018-05-23 11:13:52.722000
Labeling from 2018-05-23 11:13:56.079000 to 2018-05-23 11:13:56.401000
Labeling from 2018-05-23 11:13:59.551000 to 2018-05-23 11:13:59.880000
Labeling from 2018-05-23 11:14:02.223000 to 2018-05-23 11:14:02.631000
Labeling from 2018-05-23 11:14:09.902000 to 2018-05-23 11:14:10.158000
Labeling from 2018-05-23 11:14:13.105000 to 2018-05-23 11:14:13.421000
Labeling from 2018-05-23 11:14:17.722000 to 2018-05-23 11:14:18.011000
Labeling from 2018-05-23 11:14:20.486000 to 2018-05-23 11:14:20.742000
Labeling from 2018-05-23 11:14:24.548000 to 2018-05-23 11:14:24.824000
Labeling from 2018-05-23 11:14:30.125000 to 2018-05-23 11:14:30.473000
Labeling from 2018-05-23 11:14:33.912000 to 2018-05-23 11:14:34.149000
Labeling from 2018-05-23 11:14:37.305000 to 2018-05-23 11:14:37.581000
Labeling from 2018-05-23 11:14:43.305000 to 2018-05-23 11:14:43.535000
Labeling from 2018-05-23 11:14:46.948000 to 2018-05-23 11:14:47.217000
Labeling from 2018-05-23 11:14:50.148000 to 2018-05-23 11:14:50.444000
Labeling from 2018-05-23 11:14:54.863000 to 2018-05-23 11:14:55.145000
Labeling from 2018-05-23 11:14:57.164000 to 2018-05-23 11:14:57.473000
Labeling from 2018-05-23 11:15:00.430000 to 2018-05-23 11:15:00.719000
Labeling from 2018-05-23 11:15:04.984000 to 2018-05-23 11:15:05.312000
Labeling from 2018-05-23 11:15:10.725000 to 2018-05-23 11:15:10.994000
Labeling from 2018-05-23 11:15:15.581000 to 2018-05-23 11:15:15.817000
Labeling from 2018-05-23 11:15:20.079000 to 2018-05-23 11:15:20.447000
Labeling from 2018-05-23 11:15:25.201000 to 2018-05-23 11:15:25.476000
Labeling from 2018-05-23 11:15:29.968000 to 2018-05-23 11:15:30.217000
Labeling from 2018-05-23 11:15:33.040000 to 2018-05-23 11:15:33.309000
Labeling from 2018-05-23 11:15:37.873000 to 2018-05-23 11:15:38.129000
Labeling from 2018-05-23 11:15:43.509000 to 2018-05-23 11:15:43.791000
Labeling from 2018-05-23 11:15:43.509000 to 2018-05-23 11:15:43.791000
Labeling from 2018-05-23 11:15:47.581000 to 2018-05-23 11:15:47.798000
Labeling from 2018-05-23 11:15:50.774000 to 2018-05-23 11:15:51.017000
Labeling from 2018-05-23 11:15:55.053000 to 2018-05-23 11:15:55.263000
Labeling from 2018-05-23 11:15:58.561000 to 2018-05-23 11:15:58.791000
Labeling from 2018-05-23 11:16:02.705000 to 2018-05-23 11:16:02.968000
Labeling from 2018-05-23 11:16:08.060000 to 2018-05-23 11:16:08.322000
Labeling from 2018-05-23 11:16:10.440000 to 2018-05-23 11:16:10.690000
Labeling from 2018-05-23 11:16:15.558000 to 2018-05-23 11:16:15.808000
Labeling from 2018-05-23 11:16:19.991000 to 2018-05-23 11:16:20.260000
Labeling from 2018-05-23 11:16:25.866000 to 2018-05-23 11:16:26.135000
Labeling from 2018-05-23 11:16:31.309000 to 2018-05-23 11:16:31.552000
Labeling from 2018-05-23 11:16:37.378000 to 2018-05-23 11:16:37.719000
Labeling from 2018-05-23 11:16:43.076000 to 2018-05-23 11:16:43.312000
Labeling from 2018-05-23 11:16:48.299000 to 2018-05-23 11:16:48.549000
Labeling from 2018-05-23 11:16:52.227000 to 2018-05-23 11:16:52.522000
Labeling from 2018-05-23 11:16:57.315000 to 2018-05-23 11:16:57.591000
Labeling from 2018-05-23 11:17:00.604000 to 2018-05-23 11:17:00.893000
Labeling from 2018-05-23 11:17:05.214000 to 2018-05-23 11:17:05.463000
Labeling from 2018-05-23 11:17:10.361000 to 2018-05-23 11:17:10.644000
Labeling from 2018-05-23 11:17:15.889000 to 2018-05-23 11:17:16.158000
Labeling from 2018-05-23 11:17:17.791000 to 2018-05-23 11:17:18.053000
Labeling from 2018-05-23 11:17:23.112000 to 2018-05-23 11:17:23.427000
Labeling from 2018-05-23 11:17:26.545000 to 2018-05-23 11:17:26.880000
Labeling from 2018-05-23 11:17:31.364000 to 2018-05-23 11:17:31.680000
Labeling from 2018-05-23 11:17:36.574000 to 2018-05-23 11:17:36.935000
Labeling from 2018-05-23 11:17:42.804000 to 2018-05-23 11:17:43.073000
Labeling from 2018-05-23 11:17:48.938000 to 2018-05-23 11:17:49.221000
Labeling from 2018-05-23 11:17:54.879000 to 2018-05-23 11:17:55.103000
Labeling from 2018-05-23 11:17:57.492000 to 2018-05-23 11:17:57.781000
Labeling from 2018-05-23 11:18:01.974000 to 2018-05-23 11:18:02.309000
Labeling from 2018-05-23 11:18:06.469000 to 2018-05-23 11:18:06.771000
Labeling from 2018-05-23 11:18:08.696000 to 2018-05-23 11:18:09.076000
Labeling from 2018-05-23 11:18:12.368000 to 2018-05-23 11:18:12.794000
Labeling from 2018-05-23 11:18:18.266000 to 2018-05-23 11:18:18.555000
Labeling from 2018-05-23 11:18:22.174000 to 2018-05-23 11:18:22.424000
Labeling from 2018-05-23 11:18:26.991000 to 2018-05-23 11:18:27.267000
Labeling from 2018-05-23 11:18:33.932000 to 2018-05-23 11:18:34.181000
Labeling from 2018-05-23 11:18:37.476000 to 2018-05-23 11:18:37.765000
Labeling from 2018-05-23 11:18:40.945000 to 2018-05-23 11:18:41.201000
Labeling from 2018-05-23 11:18:46.148000 to 2018-05-23 11:18:46.417000
Labeling from 2018-05-23 11:18:52.125000 to 2018-05-23 11:18:52.421000
Labeling from 2018-05-23 11:19:51.009000 to 2018-05-23 11:19:51.292000
Labeling from 2018-05-23 11:19:53.324000 to 2018-05-23 11:19:53.639000
Labeling from 2018-05-23 11:19:57.944000 to 2018-05-23 11:19:58.233000
Labeling from 2018-05-23 11:20:01.757000 to 2018-05-23 11:20:02.020000
Labeling from 2018-05-23 11:20:05.888000 to 2018-05-23 11:20:06.236000
Labeling from 2018-05-23 11:24:12.655000 to 2018-05-23 11:24:12.892000
Labeling from 2018-05-23 11:24:17.295000 to 2018-05-23 11:24:17.577000
Labeling from 2018-05-23 11:24:21.800000 to 2018-05-23 11:24:22.128000
Labeling from 2018-05-23 11:25:18.459000 to 2018-05-23 11:25:18.774000
Labeling from 2018-05-23 11:26:19.711000 to 2018-05-23 11:26:20.092000
Labeling from 2018-05-23 11:26:24.173000 to 2018-05-23 11:26:24.443000
Labeling from 2018-05-23 11:26:29.508000 to 2018-05-23 11:26:29.980000
Labeling from 2018-05-23 11:27:29.413000 to 2018-05-23 11:27:29.761000
Labeling from 2018-05-23 11:27:39.147000 to 2018-05-23 11:27:39.502000
Labeling from 2018-05-23 11:27:42.167000 to 2018-05-23 11:27:42.364000
Labeling from 2018-05-23 11:27:54.032000 to 2018-05-23 11:27:54.321000
Labeling from 2018-05-23 11:28:03.826000 to 2018-05-23 11:28:04.121000
Labeling from 2018-05-23 11:28:06.878000 to 2018-05-23 11:28:07.318000
Labeling from 2018-05-23 11:28:30.632000 to 2018-05-23 11:28:31.026000
Labeling from 2018-05-23 11:28:34.360000 to 2018-05-23 11:28:34.734000
Labeling from 2018-05-23 11:28:40.009000 to 2018-05-23 11:28:40.351000
Labeling from 2018-05-23 11:28:47.245000 to 2018-05-23 11:28:47.587000
Labeling from 2018-05-23 11:28:53.137000 to 2018-05-23 11:28:53.492000
Labeling from 2018-05-23 11:28:58.655000 to 2018-05-23 11:28:59.010000
Labeling from 2018-05-23 11:29:07.154000 to 2018-05-23 11:29:07.574000
Labeling from 2018-05-23 11:29:22.386000 to 2018-05-23 11:29:22.761000
Labeling from 2018-05-23 11:29:28.767000 to 2018-05-23 11:29:29.128000
Labeling from 2018-05-23 11:29:36.183000 to 2018-05-23 11:29:36.597000
Labeling from 2018-05-23 11:29:45.577000 to 2018-05-23 11:29:45.938000
Labeling from 2018-05-23 11:30:01.137000 to 2018-05-23 11:30:01.538000
Labeling from 2018-05-23 11:30:19.940000 to 2018-05-23 11:30:20.328000
Labeling from 2018-05-23 11:30:28.327000 to 2018-05-23 11:30:28.616000
Labeling from 2018-05-23 11:30:37.295000 to 2018-05-23 11:30:37.570000
Labeling from 2018-05-23 11:30:45.177000 to 2018-05-23 11:30:45.439000
Labeling from 2018-05-23 11:30:48.560000 to 2018-05-23 11:30:48.836000
Labeling from 2018-05-23 11:30:57.111000 to 2018-05-23 11:30:57.492000
Labeling from 2018-05-23 11:31:03.340000 to 2018-05-23 11:31:03.636000
Labeling from 2018-05-23 11:31:09.947000 to 2018-05-23 11:31:10.302000
Labeling from 2018-05-23 11:31:19.819000 to 2018-05-23 11:31:20.161000
Labeling from 2018-05-23 11:31:29.622000 to 2018-05-23 11:31:30.030000
Labeling from 2018-05-23 11:31:51 to 2018-05-23 11:31:51.439000
Labeling from 2018-05-23 11:31:58.960000 to 2018-05-23 11:31:59.243000
Labeling from 2018-05-23 11:32:02.049000 to 2018-05-23 11:32:02.384000
Labeling from 2018-05-23 11:32:08.177000 to 2018-05-23 11:32:08.584000
Labeling from 2018-05-23 11:32:15.262000 to 2018-05-23 11:32:15.721000
Labeling from 2018-05-23 11:32:22.262000 to 2018-05-23 11:32:22.557000
Labeling from 2018-05-23 11:32:31.059000 to 2018-05-23 11:32:31.367000
Labeling from 2018-05-23 11:32:40.111000 to 2018-05-23 11:32:40.420000
Labeling from 2018-05-23 11:32:48.544000 to 2018-05-23 11:32:48.977000
Labeling from 2018-05-23 11:33:04.485000 to 2018-05-23 11:33:04.964000
Labeling from 2018-05-23 11:33:15.586000 to 2018-05-23 11:33:15.908000
Labeling from 2018-05-23 11:33:21.803000 to 2018-05-23 11:33:22.118000
Labeling from 2018-05-23 11:33:30.960000 to 2018-05-23 11:33:31.256000
Labeling from 2018-05-23 11:33:37.150000 to 2018-05-23 11:33:37.557000
Labeling from 2018-05-23 11:33:48.836000 to 2018-05-23 11:33:49.216000
Labeling from 2018-05-23 11:33:56.291000 to 2018-05-23 11:33:56.613000
Labeling from 2018-05-23 11:34:08.288000 to 2018-05-23 11:34:08.590000
Labeling from 2018-05-23 11:34:17.793000 to 2018-05-23 11:34:18.108000
Labeling from 2018-05-23 11:34:24.157000 to 2018-05-23 11:34:24.492000
Labeling from 2018-05-23 11:34:30.708000 to 2018-05-23 11:34:31.049000
Labeling from 2018-05-23 11:34:40.514000 to 2018-05-23 11:34:40.849000
Labeling from 2018-05-23 11:34:48.124000 to 2018-05-23 11:34:48.584000
Labeling from 2018-05-23 11:34:54 to 2018-05-23 11:34:54.282000
Labeling from 2018-05-23 11:34:59.396000 to 2018-05-23 11:34:59.731000
Labeling from 2018-05-23 11:35:08.429000 to 2018-05-23 11:35:08.751000
Labeling from 2018-05-23 11:35:14.744000 to 2018-05-23 11:35:15.046000

In [94]:
SE038_a2_ground_truth_df.head(-1)

                        timestamp  ground_truth
0      2018-05-23 11:05:57.000000             0
1      2018-05-23 11:05:57.003906             0
2      2018-05-23 11:05:57.007812             0
3      2018-05-23 11:05:57.011718             0
4      2018-05-23 11:05:57.015625             0
...                           ...           ...
468474 2018-05-23 11:36:26.976562             0
468475 2018-05-23 11:36:26.980468             0
468476 2018-05-23 11:36:26.984375             0
468477 2018-05-23 11:36:26.988281             0
468478 2018-05-23 11:36:26.992187             0

[468479 rows x 2 columns]

In [95]:
print(SE038_a2_ground_truth_df.shape)
print(SE038_a2_df.shape)

(468480, 2)
(468480, 17)

In [96]:
SE038_a2_ground_truth_df.to_csv(
    RAW_KISPI_DATA_FOLDER / "SE038_a2_ground_truth.csv",
    date_format="%Y-%m-%d %H:%M:%S.%f")

### Merge Annotator-2 Dataframes

In [97]:
#bipolar_SE008_a2 = SE008_a2_df.copy()    
bipolar_SE021_a2 = SE021_a2_df.copy()    
#bipolar_SE026_a2 = SE026_a2_df.copy()    
bipolar_SE038_a2 = SE038_a2_df.copy()

In [98]:
#bipolar_SE008_a2_merged = pd.merge(bipolar_SE008_a2, SE008_a2_ground_truth_df, left_index=True, right_on="timestamp") 
bipolar_SE021_a2_merged = pd.merge(bipolar_SE021_a2, SE021_a2_ground_truth_df, left_index=True, right_on="timestamp")
#bipolar_SE026_a2_merged = pd.merge(bipolar_SE026_a2, SE026_a2_ground_truth_df, left_index=True, right_on="timestamp")
bipolar_SE038_a2_merged = pd.merge(bipolar_SE038_a2, SE038_a2_ground_truth_df, left_index=True, right_on="timestamp")

In [99]:
#print(bipolar_SE008_a2_merged.shape)
print(bipolar_SE021_a2_merged.shape)
#print(bipolar_SE026_a2_merged.shape)
print(bipolar_SE038_a2_merged.shape)

(368640, 19)
(468480, 19)

#### Drop Datetime Index
We now drop the current datatime index.

This will allows us to create our `data_learning` (Train) and `data_testing` (Test) datasets.

In [100]:
#bipolar_SE008_a2_merged.reset_index(drop=True, inplace=True)
#print(bipolar_SE008_a2_merged.head(-1))

bipolar_SE021_a2_merged.reset_index(drop=True, inplace=True)
print(bipolar_SE021_a2_merged.head(-1))

#bipolar_SE026_a2_merged.reset_index(drop=True, inplace=True)

bipolar_SE038_a2_merged.reset_index(drop=True, inplace=True)

           Fp1-F7      F7-T3      T3-T5      Fp1-F3       F3-C3       C3-P3  \
0       34.186771  62.287937 -63.898834  141.758759 -108.645912  150.887161
1       35.260700  60.856033 -67.836578  140.863815 -109.361870  148.560303
2       34.902725  59.066147 -69.626465  139.789886 -110.077820  146.412445
3       35.260704  56.918289 -68.731522  138.536957 -109.540855  147.307404
4       36.155640  56.202335 -65.509727  139.431915 -108.287941  148.560303
...           ...        ...        ...         ...         ...         ...
368634  64.077820  40.451363 -72.132294  130.303497 -151.961090  175.229584
368635  63.361866  41.346306 -70.700394  130.482498 -149.634247  173.618683
368636  61.750973  42.062252 -69.626457  130.303497 -146.233459  172.007782
368637  60.319065  40.272377 -68.373543  130.482483 -147.307388  171.291824
368638  59.603111  38.482491 -66.225677  131.198441 -149.634232  172.365753

            P3-O1       Fz-Cz      Cz-Pz      Fp2-F4      F4-C4      C4-P4  \
0      -32.575874  141.937744 -18.972763  218.186768 -26.848248  28.459148
1      -31.322960  138.536957 -25.953306  219.618683 -27.385212  23.626461
2      -30.785988  138.000000 -28.459145  221.229568 -26.669258  20.941635
3      -32.396889  137.821014 -23.805447  224.809341 -25.416340  20.225681
4      -33.470818  138.536957 -16.108950  228.210114 -23.805450  19.688721
...           ...         ...        ...         ...        ...        ...
368634 -33.649811  124.396881  13.782101  196.171204 -25.774315  47.968872
368635 -32.754868  120.101166  16.466927  195.276260 -25.237350  46.178986
368636 -34.007782  122.070045   7.696498  195.634247 -26.311283  45.999996
368637 -35.618675  122.428017   1.789883  195.634247 -28.638134  45.463039
368638 -36.513618  124.754868   4.474709  195.813232 -28.101168  47.789879

            P4-O2     Fp2-F8      F8-T4       T4-T6       T6-O2  \
0      -39.735413  90.389099  97.190659  143.369644 -150.887146
1      -38.124519  90.210129  95.579765  142.832687 -150.887161
2      -39.556419  89.494164  96.653694  142.295715 -152.498047
3      -42.241245  92.357986  97.369652  141.221786 -153.571976
4      -43.852142  95.758759  96.832687  142.295715 -154.645920
...           ...        ...        ...         ...         ...
368634  -6.801559  93.431908  93.789886  154.108948 -129.766541
368635  -5.190659  92.894943  95.579773  151.245148 -128.692612
368636  -5.369644  94.505829  94.684830  150.171204 -129.408554
368637  -6.622574  94.147865  94.326843  148.023346 -130.661484
368638 -11.813225  95.221794  92.536964  148.202332 -132.272369

                        timestamp  ground_truth
0      2015-09-01 16:06:27.000000             0
1      2015-09-01 16:06:27.003906             0
2      2015-09-01 16:06:27.007812             0
3      2015-09-01 16:06:27.011718             0
4      2015-09-01 16:06:27.015625             0
...                           ...           ...
368634 2015-09-01 16:30:26.976562             0
368635 2015-09-01 16:30:26.980468             0
368636 2015-09-01 16:30:26.984375             0
368637 2015-09-01 16:30:26.988281             0
368638 2015-09-01 16:30:26.992187             0

[368639 rows x 19 columns]

#### Drop `Timestamp` column

In [101]:
#bipolar_SE008_a2_merged.drop(columns="timestamp", inplace=True)
#print(bipolar_SE008_a2_merged.head(-1))

bipolar_SE021_a2_merged.drop(columns="timestamp", inplace=True)
print(bipolar_SE021_a2_merged.head(-1))

#bipolar_SE026_a2_merged.drop(columns="timestamp", inplace=True) 
#print(bipolar_SE026_a2_merged.head(-1)) 

bipolar_SE038_a2_merged.drop(columns="timestamp", inplace=True)
print(bipolar_SE038_a2_merged.head(-1))

           Fp1-F7      F7-T3      T3-T5      Fp1-F3       F3-C3       C3-P3  \
0       34.186771  62.287937 -63.898834  141.758759 -108.645912  150.887161
1       35.260700  60.856033 -67.836578  140.863815 -109.361870  148.560303
2       34.902725  59.066147 -69.626465  139.789886 -110.077820  146.412445
3       35.260704  56.918289 -68.731522  138.536957 -109.540855  147.307404
4       36.155640  56.202335 -65.509727  139.431915 -108.287941  148.560303
...           ...        ...        ...         ...         ...         ...
368634  64.077820  40.451363 -72.132294  130.303497 -151.961090  175.229584
368635  63.361866  41.346306 -70.700394  130.482498 -149.634247  173.618683
368636  61.750973  42.062252 -69.626457  130.303497 -146.233459  172.007782
368637  60.319065  40.272377 -68.373543  130.482483 -147.307388  171.291824
368638  59.603111  38.482491 -66.225677  131.198441 -149.634232  172.365753

            P3-O1       Fz-Cz      Cz-Pz      Fp2-F4      F4-C4      C4-P4  \
0      -32.575874  141.937744 -18.972763  218.186768 -26.848248  28.459148
1      -31.322960  138.536957 -25.953306  219.618683 -27.385212  23.626461
2      -30.785988  138.000000 -28.459145  221.229568 -26.669258  20.941635
3      -32.396889  137.821014 -23.805447  224.809341 -25.416340  20.225681
4      -33.470818  138.536957 -16.108950  228.210114 -23.805450  19.688721
...           ...         ...        ...         ...        ...        ...
368634 -33.649811  124.396881  13.782101  196.171204 -25.774315  47.968872
368635 -32.754868  120.101166  16.466927  195.276260 -25.237350  46.178986
368636 -34.007782  122.070045   7.696498  195.634247 -26.311283  45.999996
368637 -35.618675  122.428017   1.789883  195.634247 -28.638134  45.463039
368638 -36.513618  124.754868   4.474709  195.813232 -28.101168  47.789879

            P4-O2     Fp2-F8      F8-T4       T4-T6       T6-O2  ground_truth
0      -39.735413  90.389099  97.190659  143.369644 -150.887146             0
1      -38.124519  90.210129  95.579765  142.832687 -150.887161             0
2      -39.556419  89.494164  96.653694  142.295715 -152.498047             0
3      -42.241245  92.357986  97.369652  141.221786 -153.571976             0
4      -43.852142  95.758759  96.832687  142.295715 -154.645920             0
...           ...        ...        ...         ...         ...           ...
368634  -6.801559  93.431908  93.789886  154.108948 -129.766541             0
368635  -5.190659  92.894943  95.579773  151.245148 -128.692612             0
368636  -5.369644  94.505829  94.684830  150.171204 -129.408554             0
368637  -6.622574  94.147865  94.326843  148.023346 -130.661484             0
368638 -11.813225  95.221794  92.536964  148.202332 -132.272369             0

[368639 rows x 18 columns]
            Fp1-F7      F7-T3       T3-T5      Fp1-F3       F3-C3       C3-P3  \
0       382.677063 -98.980545  164.490280  104.529190 -122.249039  479.330750
1       374.980530 -85.914398  163.953308  108.108948  -32.575874  389.657593
2       392.879395 -87.346306  158.941620   93.252914  -97.190659  480.941620
3       410.062256 -94.147865  158.225677   76.607010 -237.338516  645.252930
4       406.661499 -90.389099  161.089493   84.303513 -270.272400  672.638184
...            ...        ...         ...         ...         ...         ...
468474   97.548637 -98.801559   41.525291   33.649807   97.190666   18.256805
468475   64.972763 -81.618675   47.789883   31.143967   89.673149   13.961090
468476   24.163424 -56.739304   52.801559   26.311283   82.513618   12.887161
468477   30.428017 -57.276264   50.832684   28.817120   84.303505   15.392998
468478   74.817123 -81.618675   43.315174   35.081711   94.684822   16.466927

             P3-O1      Fz-Cz      Cz-Pz     Fp2-F4       F4-C4      C4-P4  \
0      -215.680923 -54.054470 -40.093388 -34.723724   69.805435 -95.400772
1      -218.723724 -56.918289 -44.210117 -25.953308   64.077820 -99.517502
2      -209.774307 -52.443581 -36.871597 -31.143967   84.482483 -96.653694
3      -199.213989 -48.326851 -26.848249 -43.494164  100.770424 -89.673149
4      -200.824921 -51.906616 -23.626461 -46.178986   91.284042 -85.019455
...            ...        ...        ...        ...         ...        ...
468474  -99.696495 -81.439690  60.140079  -5.011671   90.747078 -18.256805
468475  -90.210121 -87.704285  49.400776   0.178989   92.000000 -22.552528
468476  -80.902725 -94.863815  35.797668   4.295721   94.147858 -28.280151
468477  -85.556427 -92.715958  39.735409   3.221788   95.221794 -29.712067
468478  -99.696495 -83.229568  52.622566  -1.252918   95.400772 -27.564201

             P4-O2      Fp2-F8      F8-T4      T4-T6       T6-O2  ground_truth
0      -160.552521   42.420242 -75.533081 -99.875488  -87.883270             0
1      -167.175095   41.346313 -71.774323 -99.517517  -98.622566             0
2      -129.587555   48.326843 -73.385208 -98.443588  -49.400780             0
3       -94.863815   54.054474 -77.322960 -96.474709   -7.517509             0
4      -108.108940   53.338531 -76.785995 -95.937744  -28.638132             0
...            ...         ...        ...        ...         ...           ...
468474 -198.140076   86.630356   0.178986 -61.929958 -155.540863             0
468475 -222.840469   95.221786  -1.610886 -64.077820 -182.747086             0
468476 -250.225677  103.813225  -2.326843 -67.299606 -214.249023             0
468477 -244.677048  101.486382  -0.357986 -68.552521 -208.521408             0
468478 -211.743195   91.821014   3.400772 -68.194550 -172.186768             0

[468479 rows x 18 columns]

## LOAD

### Create Parquet Files
From transformed dataframes

In [102]:
bipolar_SE008_a1_merged.to_parquet(PROCESSED_KISPI_DATA_FOLDER / "SE008_a1_merged.parquet")

bipolar_SE021_a1_merged.to_parquet(PROCESSED_KISPI_DATA_FOLDER / "SE021_a1_merged.parquet")

bipolar_SE026_a1_merged.to_parquet(PROCESSED_KISPI_DATA_FOLDER / "SE026_a1_merged.parquet")

bipolar_SE038_a1_merged.to_parquet(PROCESSED_KISPI_DATA_FOLDER / "SE038_a1_merged.parquet")

In [103]:
#bipolar_SE008_a2_merged.to_parquet(PROCESSED_KISPI_DATA_FOLDER / "SE008_a2_merged.parquet")

bipolar_SE021_a2_merged.to_parquet(PROCESSED_KISPI_DATA_FOLDER / "SE021_a2_merged.parquet")

#bipolar_SE026_a2_merged.to_parquet(PROCESSED_KISPI_DATA_FOLDER / "SE026_a2_merged.parquet")

bipolar_SE038_a2_merged.to_parquet(PROCESSED_KISPI_DATA_FOLDER / "SE038_a2_merged.parquet")

### Create data_attributes.csv file for kispi data  
- [x] with the following code make a data_attributes.csv file

In [2]:
def create_data_attributes_csv(parquet_files, output_folder):
    """
    Creates a CSV file named 'data_attributes_kispi.csv' from multiple Parquet files
    containing patient data.

    Args:
        parquet_files: List of paths to the Parquet files.
        output_folder: Path to the output folder.
    """
    data_attributes_list = []

    for i, parquet_file in enumerate(parquet_files):
        reader = ParquetReader(parquet_file)
        file_header = reader.get_file_header()
        signal_headers = reader.get_signal_headers()

        try:
            patient_id_parts = file_header['patientcode'].split(' ')[0] + "_" + file_header['patientcode'].split(' ')[1]
        except KeyError:
            print("KeyError: 'patientcode' key not found in file header.")
            patient_id_parts = parquet_file.stem
        unique_patient_id = patient_id_parts
        start_datetime = file_header['startdate'].strftime('%Y-%m-%d %H:%M:%S')

        # get end sample and sample rate
        df = pd.read_parquet(parquet_file)
        end_sample = df.index[-1]  # get last datetime index
        sample_rate = signal_headers[0]['sample_rate']

        # create a dictionary with patient ID, start date, end sample, and sample rate
        data_attributes = {
            'unique_patient_id': unique_patient_id,
            'patient_id': f"P{i + 1}",
            'start_datetime': start_datetime,
            'end_sample': end_sample,
            'sample_rate': sample_rate
        }
        data_attributes_list.append(data_attributes)

    # Create the output directory if it doesn't exist
    output_dir = os.path.dirname(output_folder)
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # create a DataFrame from the list of dictionaries
    data_attributes_df = pd.DataFrame(data_attributes_list)

    try:
        data_attributes_df.to_csv(output_folder, index=False)
    except PermissionError:
        print(f"Permission denied: Unable to write to {output_dir}")

    print(f"Data attributes saved to {output_folder}")

In [3]:

# Define the input and output folders
input_folder = PROCESSED_KISPI_DATA_FOLDER
output_folder = PROCESSED_KISPI_DATA_FOLDER / Path("data_attributes_kispi.csv")

parequet_filenames = [input_folder / filename for filename in os.listdir(input_folder) if  filename.endswith('.parquet') - filename.__contains__('merged')]

parequet_filenames

[WindowsPath('C:/Users/c_arz/Documents/KISPI/Burst_Suppression_Project/Thesis/UnsuperDL-EEG-BSUPP/data/processed_kispi/SE008_a1.parquet'),
 WindowsPath('C:/Users/c_arz/Documents/KISPI/Burst_Suppression_Project/Thesis/UnsuperDL-EEG-BSUPP/data/processed_kispi/SE021_a1.parquet'),
 WindowsPath('C:/Users/c_arz/Documents/KISPI/Burst_Suppression_Project/Thesis/UnsuperDL-EEG-BSUPP/data/processed_kispi/SE021_a2.parquet'),
 WindowsPath('C:/Users/c_arz/Documents/KISPI/Burst_Suppression_Project/Thesis/UnsuperDL-EEG-BSUPP/data/processed_kispi/SE026_a1.parquet'),
 WindowsPath('C:/Users/c_arz/Documents/KISPI/Burst_Suppression_Project/Thesis/UnsuperDL-EEG-BSUPP/data/processed_kispi/SE038_a1.parquet'),
 WindowsPath('C:/Users/c_arz/Documents/KISPI/Burst_Suppression_Project/Thesis/UnsuperDL-EEG-BSUPP/data/processed_kispi/SE038_a2.parquet')]

In [6]:
create_data_attributes_csv(parequet_filenames, output_folder)

Data attributes saved to C:\Users\c_arz\Documents\KISPI\Burst_Suppression_Project\Thesis\UnsuperDL-EEG-BSUPP\data\processed_kispi\data_attributes_kispi.csv